import { describe,expect,it } from 'vitest';
import { jsonDigest, type QualityEvidence } from '@cirujano/core';
import { collectGitHubInput } from './github-read.js';
import { githubFixture,baseSha,repository } from './github-read.test-helper.js';
import { decodeExecutionProfile,decodeSandboxPermit,validateProfileCommands,compareQuality,decodeHarnessEnvelope,completeCommands,buildSandboxPayload } from './execution-profile.js';
async function fixture(){const github=githubFixture(),context=await collectGitHubInput({repository,ref:baseSha,workflow:'.github/workflows/ci.yml',job:'test',runs:[99]},{pageRunner:github.pageRunner,toolSourceSha:'1'.repeat(40),bundleDigest:'2'.repeat(64)});const original=JSON.parse(github.files['.cirujano/optimization-profile.json']!);const quality:QualityEvidence={commandDigest:jsonDigest([['pnpm','install','--frozen-lockfile'],...original.commands]),tests:[{id:'owned fixture',outcome:'passed'}],coverage:[{path:'src/owned.ts',statements:2,coveredStatements:2,branches:2,coveredBranches:1,functions:1,coveredFunctions:1,lines:2,coveredLines:2}]};const profile={schemaVersion:1,kind:'execution-profile',provenance:context.input.provenance,proposalDigest:'3'.repeat(64),candidateSha:'b'.repeat(40),candidateRepository:'/owned/proof',project:'owned-project',image:{uuid:'12345678-9abc-baba-deda-0123456789ab',ociDigest:'4'.repeat(64),registryReference:'docker://registry.invalid/owned@sha256:'+'4'.repeat(64),importOperationId:'12345678-9abc-baba-deda-0123456789ac',recipeHash:'5'.repeat(64),manifestHash:'6'.repeat(64),dependencyStoreHash:'7'.repeat(64),harnessHash:'8'.repeat(64)},verificationProfile:original,expectedQuality:quality,timeoutSeconds:600,maxLayerBytes:104857600,imageRetention:'owner-retained'};return{github,context,quality,profile};}
describe('approved offline execution contract',()=>{
 it('keeps original check argv and always includes frozen install',async()=>{const f=await fixture(),p=decodeExecutionProfile(f.profile);validateProfileCommands(f.github.source,p.verificationProfile,'test');expect(completeCommands(p.verificationProfile)).toEqual([['pnpm','install','--frozen-lockfile'],['pnpm','test']]);});
 it.each(['uuid','digest','recipe-only','path','commands','quality','extra'])('rejects %s malformed profile',async mutation=>{const f=await fixture();const p=f.profile as unknown as Record<string,unknown>;if(mutation==='uuid')f.profile.image.uuid='tag';else if(mutation==='digest')f.profile.image.registryReference='docker://registry.invalid/owned:latest';else if(mutation==='recipe-only')delete p.image;else if(mutation==='path')f.profile.candidateRepository='relative';else if(mutation==='commands')f.profile.verificationProfile.commands=[['sh','-c','evil']];else if(mutation==='quality')f.profile.expectedQuality.tests=[];else p.extra='unknown';expect(()=>decodeExecutionProfile(p)).toThrow();});
 it('rejects a valid profile that omits or alters a workflow check',async()=>{const f=await fixture();f.profile.verificationProfile.commands=[['pnpm','run','other']];expect(()=>validateProfileCommands(f.github.source,f.profile.verificationProfile,'test')).toThrow();});
 it('rejects a conditional/multiline workflow check instead of skipping it',async()=>{const f=await fixture();expect(()=>validateProfileCommands(f.github.source.replace('run: pnpm test','if: false\n        run: pnpm test'),f.profile.verificationProfile,'test')).toThrow();});
 it.each(['deleted-test','skipped-test','denominator','counter','command'])('blocks quality mutant %s',async mutation=>{const f=await fixture();const candidate=structuredClone(f.quality);if(mutation==='deleted-test')candidate.tests=[];else if(mutation==='skipped-test')candidate.tests[0]!.outcome='skipped';else if(mutation==='denominator')candidate.coverage[0]!.statements=1;else if(mutation==='counter')candidate.coverage[0]!.coveredBranches=0;else candidate.commandDigest='9'.repeat(64);expect(()=>compareQuality(f.quality,candidate)).toThrow();});
 it('binds exact execution permit limits and expiry',async()=>{const f=await fixture(),p=decodeExecutionProfile(f.profile),permit={schemaVersion:1,kind:'sandbox-permit',permitId:'owned-test',repositoryId:p.provenance.repositoryId,proposalDigest:p.proposalDigest,profileDigest:jsonDigest(p),candidateSha:p.candidateSha,imageUuid:p.image.uuid,project:p.project,expiresAt:'2026-09-29T23:00:00Z',maxOperations:2};expect(decodeSandboxPermit(permit,p,Date.parse('2026-09-29T20:00:00Z')).maxOperations).toBe(2);expect(()=>decodeSandboxPermit({...permit,imageUuid:'12345678-9abc-baba-deda-0123456789ad'},p,Date.parse('2026-09-29T20:00:00Z'))).toThrow();expect(()=>decodeSandboxPermit(permit,p,Date.parse('2026-09-30T00:00:00Z'))).toThrow();});
 it.each(['test-report','coverage-report','reserved-home','reserved-store','directory-source'])('rejects unsupported payload %s before a paid create',async mutation=>{const f=await fixture(),p=decodeExecutionProfile(f.profile),files=structuredClone(f.context.source.files);if(mutation==='directory-source')p.verificationProfile.sourcePaths=['src'];else {const path=mutation==='test-report'?p.verificationProfile.testReportPath:mutation==='coverage-report'?p.verificationProfile.coverageReportPath:mutation==='reserved-home'?'.home/cache':'.pnpm-store/cache';files.push({path,mode:'100644',hash:'9'.repeat(64),bytesBase64:Buffer.from('{}').toString('base64')});}expect(()=>buildSandboxPayload(p,files,'base')).toThrow('unsupported-execution-profile');});
 it('rejects a forged incomplete harness success envelope',async()=>{const f=await fixture();expect(()=>decodeHarnessEnvelope({kind:'harness-result',quality:f.quality},decodeExecutionProfile(f.profile),'base','1'.repeat(64),'2'.repeat(64))).toThrow();});
});
