import { describe,it,expect } from 'vitest';
import { join } from 'node:path';
import { runMeasure,readMeasurementContext } from './measure.js';
import { artifactNaming, measurementFixture } from './measure.test-helper.js';
import { readPrivateJson } from './store.js';
import { canonicalJson } from '@cirujano/core';
const options=(f:Awaited<ReturnType<typeof measurementFixture>>)=>({pageRunner:f.pageRunner,binaryRunner:f.binaryRunner,now:()=>Date.parse('2026-09-29T22:00:00Z')});
// Multi-stage fixtures use real Git objects and product private-store validation.
describe('exact cohort GitHub reader and private lifecycle',{timeout:30000},()=>{
 it('uses only GET and retains all six authenticated samples and rounding',async()=>{const f=await measurementFixture();try{const result=await runMeasure(join(f.proposed,'proposal.json'),join(f.verified,'sandbox.json'),f.cohort,f.measured,options(f));expect(result.status).toBe('measured-improvement');const retained=await readMeasurementContext(result.artifactPath!);expect(retained.measurement.samples).toEqual(f.rows);expect(retained.measurement.githubListSavingUsd).toBe(0);expect(f.calls.every(args=>args[args.indexOf('--method')+1]==='GET')).toBe(true);expect((await readPrivateJson(join(f.measured,'intent.json'))as {cohortDigest:string}).cohortDigest).toHaveLength(64);}finally{f.git('status','--porcelain');}});
 it.each(['attempt','head','runner','coverage','check','archive','step','cold'])('blocks %s evidence mutant',async mutation=>{const f=await measurementFixture();const index=3,id=204;if(mutation==='attempt')f.cohort.entries[index]!.attempt=2;else if(mutation==='head')f.rows[index]!.headSha='9'.repeat(40);else if(mutation==='runner')f.payloads.get(id)!.runnerImage='other-image';else if(mutation==='coverage')(f.payloads.get(id)!.quality as typeof f.quality).coverage[0]!.statements=2;else if(mutation==='cold')f.rows[index]!.cacheObservation='hit';let pageRunner=f.pageRunner;if(mutation==='check'||mutation==='step')pageRunner=async(command,args,settings)=>{const response=await f.pageRunner(command,args,settings);const parsed=JSON.parse(response.stdout);if(mutation==='check'&&parsed.check_runs)parsed.check_runs[0].conclusion='failure';if(mutation==='step'&&parsed.jobs)parsed.jobs[0].steps[3].name='Run weakened install';return{stdout:JSON.stringify(parsed)};};if(mutation==='archive')f.binaries.set(id,Buffer.from('unsafe'));else if(mutation==='runner'||mutation==='coverage'){const {ownedZip}=await import('./artifact-zip.test-helper.js');f.binaries.set(id,ownedZip(Buffer.from(canonicalJson(f.payloads.get(id)))));}const result=await runMeasure(join(f.proposed,'proposal.json'),join(f.verified,'sandbox.json'),f.cohort,f.measured,{...options(f),pageRunner});const comparisonRejection=mutation==='coverage'||mutation==='cold';expect(result.status).toBe(comparisonRejection?'rejected':'failed');expect(result.reasonCode).toBe(comparisonRejection?'rejected':'measurement-evidence-incomplete');});
 it('accepts the benchmark template plain quality artifact name, still bound by its content',async()=>{const f=await measurementFixture();artifactNaming.plain=true;try{const result=await runMeasure(join(f.proposed,'proposal.json'),join(f.verified,'sandbox.json'),f.cohort,f.measured,options(f));expect(result.status).toBe('measured-improvement');}finally{artifactNaming.plain=false;}});
 it('rejects malformed cohort before any external read or output',async()=>{const f=await measurementFixture();f.cohort.entries.pop();const result=await runMeasure(join(f.proposed,'proposal.json'),join(f.verified,'sandbox.json'),f.cohort,f.measured,options(f));expect(result.status).toBe('rejected');expect(f.calls).toEqual([]);});
 it('retains a failed sample rather than substituting another successful run',async()=>{const f=await measurementFixture();f.rows[4]!.conclusion='failure';const result=await runMeasure(join(f.proposed,'proposal.json'),join(f.verified,'sandbox.json'),f.cohort,f.measured,options(f));expect(result.status).toBe('rejected');expect(result.artifactPath).not.toBeNull();const raw=await readPrivateJson(result.artifactPath!)as {samples:typeof f.rows};expect(raw.samples).toHaveLength(6);expect(raw.samples[4]!.conclusion).toBe('failure');});
 it('detects schema-valid retained samples tampering',async()=>{const f=await measurementFixture();const result=await runMeasure(join(f.proposed,'proposal.json'),join(f.verified,'sandbox.json'),f.cohort,f.measured,options(f));const {writeFile}=await import('node:fs/promises');const raw=await readPrivateJson(join(f.measured,'measurement-evidence.json'))as {samples:typeof f.rows};raw.samples[0]!.cacheObservation='hit';await writeFile(join(f.measured,'measurement-evidence.json'),JSON.stringify(raw));await expect(readMeasurementContext(result.artifactPath!)).rejects.toThrow();});
});
