import { canonicalJson,jsonDigest,sha256,type MeasurementSample } from '@cirujano/core';
import { join } from 'node:path';
import { verificationFixture } from './verify.test-helper.js';
import { verifyPair,readSandboxContext } from './verify.js';
import { readProposalContext } from './propose.js';
import { ownedZip } from './artifact-zip.test-helper.js';
import type { GitHubPageRunner } from '../github-api.js';
import type { GitHubBinaryRunner } from './measure.js';
export async function measurementFixture(){
 const f=await verificationFixture({singleJob:true});f.quality.coverage[0]!.path=f.profile.verificationProfile.sourcePaths[0]!;f.permit.profileDigest=jsonDigest(f.profile);
 const result=await verifyPair(join(f.proposed,'proposal.json'),f.profile,f.permit,f.verified,{iamToken:'owned-synthetic-IAM',fetch:f.fetcher,permitLedger:join(f.directory,'sandbox-ledger')});if(result.status!=='sandbox-verified')throw new Error('owned sandbox fixture failed');
 const context=await readProposalContext(join(f.proposed,'proposal.json')),pair=await readSandboxContext(result.artifactPath!);const p=context.proposal.provenance,cohort={schemaVersion:1,kind:'measurement-cohort',provenance:p,proposalDigest:jsonDigest(f.proposal),sandboxDigest:jsonDigest(pair.sandbox),candidateSha:f.profile.candidateSha,recordedAt:'2026-09-29T00:00:00Z',entries:Array.from({length:6},(_,index)=>({role:index<3?'base':'candidate',runId:201+index,attempt:1})),runner:{os:'Linux',architecture:'X64',image:'ubuntu24/20260920.1'}};
 const calls:string[][]=[],payloads=new Map<number,Record<string,unknown>>(),rows:MeasurementSample[]=[];
 for(let index=0;index<6;index++){const role=index<3?'base':'candidate',headSha=role==='base'?p.baseSha:f.profile.candidateSha,runId=201+index,startedAt=new Date(Date.parse('2026-09-29T01:00:00Z')+index*600000).toISOString(),elapsedMs=role==='base'?120000:60000,completedAt=new Date(Date.parse(startedAt)+elapsedMs).toISOString();const envelope={schemaVersion:1,kind:'github-quality',repositoryId:p.repositoryId,repository:p.repository,runId,attempt:1,headSha,workflowPath:p.workflowPath,workflowHash:role==='base'?p.workflowHash:f.proposal.candidateWorkflowHash,jobId:p.jobId,sourceTreeDigest:p.sourceTreeDigest,lockfileHash:p.lockfileHash,profileHash:p.verificationProfileHash,toolSourceSha:p.toolSourceSha,bundleDigest:p.bundleDigest,runnerOs:'Linux',runnerArchitecture:'X64',runnerImage:cohort.runner.image,nodeVersion:f.profile.verificationProfile.nodeVersion,pnpmVersion:f.profile.verificationProfile.pnpmVersion,workflowContractDigest:f.proposal.beforeStructuralDigest,quality:structuredClone(f.quality)};payloads.set(runId,envelope);rows.push({role,runId,attempt:1,jobId:500+index,headSha,startedAt,completedAt,elapsedMs,roundedMinutes:Math.ceil(elapsedMs/60000),queueMs:2000,endToEndMs:elapsedMs+3000,conclusion:'success',runnerOs:'Linux',runnerArchitecture:'X64',runnerImage:cohort.runner.image,nodeVersion:envelope.nodeVersion,pnpmVersion:envelope.pnpmVersion,workflowContractDigest:envelope.workflowContractDigest,sourceTreeDigest:p.sourceTreeDigest,lockfileHash:p.lockfileHash,requiredChecks:[{name:'test',conclusion:'success'}],cacheObservation:role==='base'?'not-applicable':index===3?'cold':'hit',quality:structuredClone(f.quality)});}
 const binaries=new Map<number,Buffer>();for(const [id,envelope]of payloads)binaries.set(id,ownedZip(Buffer.from(canonicalJson(envelope))));
 const pageRunner:GitHubPageRunner=async(_command,args)=>{calls.push(args);const endpoint=args.find(value=>value.startsWith('repos/'))!;let body:unknown;
  if(endpoint===`repos/${p.repository}`)body={id:p.repositoryId,full_name:p.repository,fork:false,private:false};
  else if(endpoint.includes('/git/commits/')){const sha=endpoint.split('/').at(-1)!;body={sha,tree:{sha:f.git('rev-parse',`${sha}^{tree}`)}};}
  else if(endpoint.includes('/git/trees/')){const tree=endpoint.split('/').at(-1)!.split('?')[0]!,entries=f.git('ls-tree','-r','-t',tree).split('\n').map(line=>{const match=/^(\d+) (blob|tree) ([a-f0-9]{40})\t(.+)$/.exec(line)!;return{mode:match[1],type:match[2],sha:match[3],path:match[4],...(match[2]==='blob'?{size:Buffer.byteLength(f.git('cat-file','blob',match[3]!)+(f.git('cat-file','blob',match[3]!).endsWith('\n')?'':'\n'))}:{})};});for(const entry of entries)if(entry.type==='blob')entry.size=Number(f.git('cat-file','-s',entry.sha!));body={sha:tree,truncated:false,tree:entries};}
  else if(endpoint.includes('/git/blobs/')){const sha=endpoint.split('/').at(-1)!,raw=f.git('cat-file','blob',sha),size=Number(f.git('cat-file','-s',sha)),bytes=Buffer.from(raw+('\n'.repeat(Math.max(0,size-Buffer.byteLength(raw)))));body={sha,size,encoding:'base64',content:bytes.toString('base64')};}
  else if(endpoint.includes('/actions/runs/')){const id=Number(/\/runs\/(\d+)/.exec(endpoint)![1]),row=rows.find(row=>row.runId===id)!;
   if(endpoint.includes('/jobs')){const names=['Run actions/checkout@'+'a'.repeat(40),'Run pnpm/action-setup@'+'b'.repeat(40),'Run actions/setup-node@820762786026740c76f36085b0efc47a31fe5020','Run pnpm install --frozen-lockfile','Run pnpm test'];body={total_count:1,jobs:[{id:row.jobId,name:'test',run_id:id,run_attempt:row.attempt,head_sha:row.headSha,status:'completed',conclusion:row.conclusion,started_at:row.startedAt,completed_at:row.completedAt,html_url:`https://github.com/${p.repository}/actions/runs/${id}/job/${row.jobId}`,labels:['ubuntu-24.04'],steps:names.map((name,index)=>({name,number:index+1,status:'completed',conclusion:'success',started_at:row.startedAt,completed_at:row.completedAt}))}]};}
   else if(endpoint.includes('/artifacts'))body={total_count:1,artifacts:[{id,name:`cirujano-quality-${id}-${row.attempt}`,expired:false,size_in_bytes:binaries.get(id)!.length,digest:`sha256:${sha256(binaries.get(id)!)}`,workflow_run:{id,repository_id:p.repositoryId,head_repository_id:p.repositoryId,head_sha:row.headSha}}]};
   else body={id,run_attempt:row.attempt,head_sha:row.headSha,path:p.workflowPath,status:'completed',conclusion:row.conclusion,event:'workflow_dispatch',created_at:new Date(Date.parse(row.startedAt)-row.queueMs).toISOString(),updated_at:new Date(Date.parse(row.startedAt)-row.queueMs+row.endToEndMs).toISOString(),check_suite_id:id,repository:{id:p.repositoryId,full_name:p.repository},head_repository:{id:p.repositoryId,full_name:p.repository,fork:false}};
  }else if(endpoint.includes('/check-runs')){const suite=Number(/\/check-suites\/(\d+)/.exec(endpoint)?.[1]);const sha=/\/commits\/([^/]+)/.exec(endpoint)?.[1];const row=rows.find(row=>row.runId===suite)??rows.find(row=>row.headSha===sha)??rows[0]!;body={total_count:1,check_runs:[{id:row.jobId,name:'test',head_sha:row.headSha,status:'completed',conclusion:row.conclusion,details_url:`https://github.com/${p.repository}/actions/runs/${row.runId}/job/${row.jobId}`} ]};}
  else throw new Error('unhandled owned GitHub read '+endpoint);return{stdout:JSON.stringify(body)};
 };
 const binaryRunner:GitHubBinaryRunner=async(_command,args)=>{calls.push(args);const endpoint=args.find(value=>value.startsWith('repos/'))!;if(endpoint.includes('/artifacts/'))return{stdout:binaries.get(Number(/\/artifacts\/(\d+)/.exec(endpoint)![1]))!};const jobId=Number(/\/jobs\/(\d+)/.exec(endpoint)![1]),row=rows.find(row=>row.jobId===jobId)!;return{stdout:Buffer.from("Current runner version: '2.329.0'\n##[group]Runner Image\nImage: ubuntu-24.04\nVersion: 20260920.1\nImage Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20260920.1\n##[endgroup]\n"+'##[group]Run actions/setup-node@820762786026740c76f36085b0efc47a31fe5020\n'+(row.cacheObservation==='cold'?'pnpm cache is not found\n':'Cache restored from key: node-cache-Linux-x64-pnpm-'+'a'.repeat(64)+'\n')+'##[group]Run pnpm install --frozen-lockfile\n')};};
 return{...f,context,pair,cohort,calls,payloads,rows,binaries,pageRunner,binaryRunner,measured:join(f.directory,'measured')};
}
