import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { join,dirname,basename } from 'node:path';
import { canonicalJson,jsonDigest,sha256,decodeCohortManifest,compareMeasurement,assertMeasuredEvidence,billableMinutesForJob,parseWorkflowSource,type MeasurementArtifact,type MeasurementSample,type ComparisonInputs,type CohortManifest,type GitHubPricing } from '@cirujano/core';
import { record,array,text,positiveInteger,timestamp } from '../github-api.js';
import { githubGet,githubPaged,readGitHubSource,type GitHubReadOptions } from './github-read.js';
import { readProposalContext,copyProposalContext,type ProposalContext } from './propose.js';
import { readSandboxContext } from './verify.js';
import { readQualityZip } from './artifact-zip.js';
import { readQualityRun,observeCacheLog,selectedCacheLog,readHostedRunnerIdentity } from './quality-run.js';
import { readPrivateJson,readOptimizationArtifact,withOperationStore,type OperationStore } from './store.js';
export type GitHubBinaryRunner=(command:string,args:string[],options:{encoding:'buffer';maxBuffer:number;timeout:number})=>Promise<{stdout:Buffer}>;
export interface MeasurementOptions extends GitHubReadOptions {binaryRunner?:GitHubBinaryRunner;now?:()=>number;pricing?:GitHubPricing|null}
export interface MeasurementDisposition{status:'measured-improvement'|'no-improvement'|'rejected'|'failed';reasonCode:string;artifactPath:string|null}
interface MeasurementIntent {schemaVersion:1;kind:'measurement-intent';cohortDigest:string;proposalDigest:string;sandboxDigest:string;startedAt:string}
interface MeasurementEvidence{schemaVersion:1;kind:'measurement-evidence';visibility:'public'|'private';pricing:GitHubPricing|null;samples:MeasurementSample[]}
export interface MeasurementContext{context:ProposalContext;pair:Awaited<ReturnType<typeof readSandboxContext>>;cohort:CohortManifest;comparison:ComparisonInputs;measurement:MeasurementArtifact;intent:MeasurementIntent;evidence:MeasurementEvidence}
const execute=promisify(execFile);
export function exact(value:unknown,keys:string[]){canonicalJson(value);if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join(',')!==[...keys].sort().join(','))throw new Error('measurement-companion-invalid');return value as Record<string,unknown>;}
export async function binary(endpoint:string,maximum:number,options:MeasurementOptions):Promise<Buffer>{
 if(!/^repos\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/(?:actions\/artifacts\/\d+\/zip|actions\/jobs\/\d+\/logs)$/.test(endpoint))throw new Error('measurement-binary-endpoint');
 // gh 2.102 refuses colored job logs without this flag; bytes are captured and parsed as data, never printed.
 const runner:GitHubBinaryRunner=options.binaryRunner??(async(command,args,settings)=>{const result=await execute(command,args,settings);return{stdout:result.stdout};});
 const {stdout}=await runner(options.ghPath??process.env['CIRUJANO_GH_PATH']??'gh',['api','--method','GET','--hostname','github.com','--allow-escape-sequences',endpoint,'-H','Accept: application/vnd.github+json','-H','X-GitHub-Api-Version: 2022-11-28'],{encoding:'buffer',maxBuffer:maximum,timeout:60000});if(!Buffer.isBuffer(stdout)||stdout.length>maximum)throw new Error('measurement-download-size');return stdout;
}
export async function retainSandboxEvidence(store:OperationStore,path:string,pair:Awaited<ReturnType<typeof readSandboxContext>>):Promise<void>{
 await withOperationStore(join(store.directory,'sandbox-evidence'),async nested=>{await copyProposalContext(nested,pair.context);await nested.writeJson('execution-profile.json',pair.profile);await nested.writeJson('sandbox-permit.json',pair.permit);await nested.writeJson('image-readback.json',await readPrivateJson(join(dirname(path),'image-readback.json')));await nested.writeArtifact('sandbox',pair.sandbox);await nested.writeJson('intent.json',{...pair.journal,latestArtifact:'sandbox.json'});});
}
async function sourceReadback(context:ProposalContext,candidateSha:string,options:MeasurementOptions):Promise<'public'|'private'>{
 const p=context.proposal.provenance,repository=await githubGet(`repos/${p.repository}`,options);if(repository.id!==p.repositoryId||repository.full_name!==p.repository||typeof repository.private!=='boolean')throw new Error('measurement-repository-drift');
 for(const [sha,workflow]of [[p.baseSha,context.source.files.find(file=>file.path===p.workflowPath)!.bytesBase64],[candidateSha,Buffer.from(context.candidate).toString('base64')]]){const actual=await readGitHubSource(p.repository,sha!,options);const expected=context.source.files.map(file=>file.path===p.workflowPath?{...file,hash:sha256(Buffer.from(workflow!,'base64')),bytesBase64:workflow!}:file);if(actual.repositoryId!==p.repositoryId||canonicalJson(actual.files)!==canonicalJson(expected))throw new Error('measurement-source-drift');}
 return repository.private?'private':'public';
}
function stepsFor(context:ProposalContext):Record<string,unknown>[]{const source=context.source.files.find(file=>file.path===context.proposal.provenance.workflowPath)!;return array(record(record(parseWorkflowSource(Buffer.from(source.bytesBase64,'base64').toString('utf8')).jobs,'workflow jobs')[context.proposal.provenance.jobId],'workflow job').steps,'workflow steps').map(step=>record(step,'step'));}
function stepName(step:Record<string,unknown>):string{return typeof step.name==='string'?step.name:typeof step.uses==='string'?`Run ${step.uses}`:`Run ${text(step.run,'step.run').split('\n')[0]}`;}
function verifySteps(job:Record<string,unknown>,expected:Record<string,unknown>[]):void{const observed=array(job.steps,'GitHub steps').map(item=>record(item,'observed step')),offset=observed[0]?.name==='Set up job'?1:0;
 for(const[index,step]of expected.entries()){const actual=observed[offset+index];if(!actual||actual.name!==stepName(step)||actual.number!==offset+index+1||actual.status!=='completed'||!['success','failure','cancelled','skipped'].includes(String(actual.conclusion))||(job.conclusion==='success'&&actual.conclusion!=='success'))throw new Error('measurement-step-contract');}
 for(const step of observed.slice(offset+expected.length))if(typeof step.name!=='string'||(!step.name.startsWith('Post ')&&step.name!=='Complete job')||step.status!=='completed'||(job.conclusion==='success'&&step.conclusion!=='success'))throw new Error('measurement-step-inventory');
}
async function sampleFor(entry:CohortManifest['entries'][number],firstCandidate:boolean,context:ProposalContext,pair:Awaited<ReturnType<typeof readSandboxContext>>,options:MeasurementOptions):Promise<MeasurementSample>{
 const p=context.proposal.provenance,expectedSha=entry.role==='base'?p.baseSha:pair.sandbox.candidateSha,prefix=`repos/${p.repository}`,run=await githubGet(`${prefix}/actions/runs/${entry.runId}/attempts/${entry.attempt}`,options),head=record(run.head_repository,'head repo'),repo=record(run.repository,'run repo');
 if(run.id!==entry.runId||run.run_attempt!==entry.attempt||run.head_sha!==expectedSha||run.path!==p.workflowPath||run.status!=='completed'||!['success','failure','cancelled','skipped'].includes(String(run.conclusion))||!['push','workflow_dispatch','schedule'].includes(String(run.event))||repo.id!==p.repositoryId||repo.full_name!==p.repository||head.id!==p.repositoryId||head.full_name!==p.repository||head.fork!==false)throw new Error('measurement-run-identity');
 const expected=stepsFor(context),workflow=record(parseWorkflowSource(Buffer.from(context.source.files.find(file=>file.path===p.workflowPath)!.bytesBase64,'base64').toString('utf8')),'workflow'),jobName=record(record(workflow.jobs,'jobs')[p.jobId],'job').name??p.jobId;
 const jobs=await githubPaged(`${prefix}/actions/runs/${entry.runId}/attempts/${entry.attempt}/jobs`,'jobs',options),targets=jobs.filter(job=>job.name===jobName);if(targets.length!==1||new Set(jobs.map(job=>job.name)).size!==jobs.length)throw new Error('measurement-job-inventory');
 for(const job of jobs)if(job.run_id!==entry.runId||job.run_attempt!==entry.attempt||job.head_sha!==expectedSha||job.status!=='completed'||!['success','failure','cancelled','skipped'].includes(String(job.conclusion)))throw new Error('measurement-job-identity');const job=targets[0]!;verifySteps(job,expected);
 const checkSuite=positiveInteger(run.check_suite_id,'check suite'),checks=await githubPaged(`${prefix}/check-suites/${checkSuite}/check-runs?filter=all`,'check_runs',options);
 if(checks.length!==jobs.length||new Set(checks.map(check=>check.name)).size!==checks.length)throw new Error('measurement-required-check-inventory');
 for(const check of checks){const actual=jobs.find(job=>job.name===check.name);if(!actual||check.head_sha!==expectedSha||check.status!=='completed'||check.conclusion!==actual.conclusion||check.details_url!==`https://github.com/${p.repository}/actions/runs/${entry.runId}/job/${positiveInteger(actual.id,'job id')}`)throw new Error('measurement-required-check-drift');}
 const artifacts=await githubPaged(`${prefix}/actions/runs/${entry.runId}/artifacts`,'artifacts',options),named=artifacts.filter(artifact=>artifact.name==='cirujano-quality'||artifact.name===`cirujano-quality-${entry.runId}-${entry.attempt}`);if(named.length!==1)throw new Error('measurement-quality-artifact-missing');const artifact=named[0]!,artifactRun=record(artifact.workflow_run,'artifact run');
 if(artifact.expired!==false||!Number.isSafeInteger(artifact.size_in_bytes)||Number(artifact.size_in_bytes)<22||Number(artifact.size_in_bytes)>8*1024*1024||typeof artifact.digest!=='string'||!/^sha256:[a-f0-9]{64}$/.test(artifact.digest)||artifactRun.id!==entry.runId||artifactRun.repository_id!==p.repositoryId||artifactRun.head_repository_id!==p.repositoryId||artifactRun.head_sha!==expectedSha)throw new Error('measurement-artifact-identity');
 const archive=await binary(`${prefix}/actions/artifacts/${positiveInteger(artifact.id,'artifact id')}/zip`,8*1024*1024,options);if(archive.length!==artifact.size_in_bytes||`sha256:${sha256(archive)}`!==artifact.digest)throw new Error('measurement-archive-hash');const envelope=readQualityRun(readQualityZip(archive));
 if(envelope.repositoryId!==p.repositoryId||envelope.repository!==p.repository||envelope.runId!==entry.runId||envelope.attempt!==entry.attempt||envelope.headSha!==expectedSha||envelope.workflowPath!==p.workflowPath||envelope.workflowHash!==(entry.role==='base'?p.workflowHash:context.proposal.candidateWorkflowHash)||envelope.jobId!==p.jobId||envelope.sourceTreeDigest!==p.sourceTreeDigest||envelope.lockfileHash!==p.lockfileHash||envelope.profileHash!==p.verificationProfileHash||envelope.toolSourceSha!==p.toolSourceSha||envelope.bundleDigest!==p.bundleDigest||envelope.workflowContractDigest!==context.proposal.beforeStructuralDigest)throw new Error('measurement-quality-identity');
 const startedAt=timestamp(job.started_at,'job start'),completedAt=timestamp(job.completed_at,'job completed'),createdAt=timestamp(run.created_at,'run created'),updatedAt=timestamp(run.updated_at,'run updated'),elapsedMs=Date.parse(completedAt)-Date.parse(startedAt),queueMs=Date.parse(startedAt)-Date.parse(createdAt),endToEndMs=Date.parse(updatedAt)-Date.parse(createdAt),roundedMinutes=billableMinutesForJob({name:String(jobName),startedAt,completedAt});if(elapsedMs<0||queueMs<0||endToEndMs<queueMs+elapsedMs||roundedMinutes===null)throw new Error('measurement-timing');
 const logs=new TextDecoder('utf8',{fatal:true}).decode(await binary(`${prefix}/actions/jobs/${positiveInteger(job.id,'job id')}/logs`,4*1024*1024,options)),runner=readHostedRunnerIdentity(logs,job.labels,text(record(record(workflow.jobs,'jobs')[p.jobId],'job')['runs-on'],'runner'));
 if(envelope.runnerOs!==runner.runnerOs||envelope.runnerArchitecture!==runner.runnerArchitecture||envelope.runnerImage!==runner.runnerImage)throw new Error('measurement-runner-drift');
 return{role:entry.role,runId:entry.runId,attempt:entry.attempt,jobId:positiveInteger(job.id,'job id'),headSha:expectedSha,startedAt,completedAt,elapsedMs,roundedMinutes,queueMs,endToEndMs,conclusion:job.conclusion as MeasurementSample['conclusion'],...runner,nodeVersion:envelope.nodeVersion,pnpmVersion:envelope.pnpmVersion,workflowContractDigest:envelope.workflowContractDigest,sourceTreeDigest:envelope.sourceTreeDigest,lockfileHash:envelope.lockfileHash,requiredChecks:checks.map(check=>({name:text(check.name,'check name'),conclusion:text(check.conclusion,'check conclusion')})).sort((a,b)=>a.name.localeCompare(b.name)),cacheObservation:entry.role==='base'?'not-applicable':observeCacheLog(selectedCacheLog(logs,'820762786026740c76f36085b0efc47a31fe5020'),firstCandidate),quality:envelope.quality};
}
export async function runMeasure(proposalPath:string,sandboxPath:string,cohortRaw:unknown,output:string,options:MeasurementOptions={}):Promise<MeasurementDisposition>{
 let context:ProposalContext,pair:Awaited<ReturnType<typeof readSandboxContext>>,cohort:CohortManifest;
 try{context=await readProposalContext(proposalPath);pair=await readSandboxContext(sandboxPath);cohort=decodeCohortManifest(cohortRaw);if(pair.sandbox.status!=='sandbox-verified'||jsonDigest(pair.context.proposal)!==jsonDigest(context.proposal)||cohort.proposalDigest!==jsonDigest(context.proposal)||cohort.sandboxDigest!==jsonDigest(pair.sandbox)||cohort.candidateSha!==pair.sandbox.candidateSha||canonicalJson(cohort.provenance)!==canonicalJson(context.proposal.provenance)||Date.parse(cohort.recordedAt)>(options.now??Date.now)())throw new Error('measurement-input-drift');}catch{return{status:'rejected',reasonCode:'measurement-input-rejected',artifactPath:null};}
 try{return await withOperationStore(output,async store=>{
  await copyProposalContext(store,context);await retainSandboxEvidence(store,sandboxPath,pair);await store.writeJson('cohort.json',cohort);const intent:MeasurementIntent={schemaVersion:1,kind:'measurement-intent',cohortDigest:jsonDigest(cohort),proposalDigest:jsonDigest(context.proposal),sandboxDigest:jsonDigest(pair.sandbox),startedAt:new Date((options.now??Date.now)()).toISOString()};await store.writeJson('intent.json',intent);
  const visibility=await sourceReadback(context,pair.sandbox.candidateSha,options),samples:MeasurementSample[]=[],errors:{runId:number;attempt:number;reason:string}[]=[];const firstCandidate=cohort.entries.find(entry=>entry.role==='candidate');
  for(const entry of cohort.entries){try{samples.push(await sampleFor(entry,entry===firstCandidate,context,pair,options));}catch(error){errors.push({runId:entry.runId,attempt:entry.attempt,reason:error instanceof Error&&/^[a-z-]+$/.test(error.message)?error.message:'measurement-read-incomplete'});}}
  if(errors.length){await store.writeJson('measurement-incomplete.json',{schemaVersion:1,kind:'measurement-incomplete',cohortDigest:jsonDigest(cohort),samples,errors});return{status:'failed',reasonCode:'measurement-evidence-incomplete',artifactPath:null}as MeasurementDisposition;}
  const evidence:MeasurementEvidence={schemaVersion:1,kind:'measurement-evidence',visibility,pricing:options.pricing??null,samples},comparison:ComparisonInputs={input:context.input,proposal:context.proposal,sandbox:pair.sandbox,cohort,samples,visibility,pricing:evidence.pricing},measurement=compareMeasurement(comparison);
  await store.writeJson('measurement-evidence.json',evidence);await store.writeArtifact('measurement',measurement);await store.writeJson('measurement-receipt.json',{schemaVersion:1,kind:'measurement-receipt',intentDigest:jsonDigest(intent),evidenceDigest:jsonDigest(evidence),measurementDigest:jsonDigest(measurement)});await store.writeJson('operation.json',{schemaVersion:1,kind:'optimization-operation',action:'measure',status:measurement.status,reasonCode:measurement.status,inputDigest:jsonDigest(context.input),nextCommand:'cirujano --help'});return{status:measurement.status,reasonCode:measurement.status,artifactPath:join(store.directory,'measurement.json')};
 });}catch{return{status:'failed',reasonCode:'measurement-stage-interrupted',artifactPath:null};}
}
export async function readMeasurementContext(path:string):Promise<MeasurementContext>{
 const directory=dirname(path);if(basename(path)!=='measurement.json')throw new Error('measurement-filename');const context=await readProposalContext(join(directory,'proposal.json')),pair=await readSandboxContext(join(directory,'sandbox-evidence','sandbox.json')),cohort=decodeCohortManifest(await readPrivateJson(join(directory,'cohort.json'))),measurement=await readOptimizationArtifact('measurement',path);
 const intent=exact(await readPrivateJson(join(directory,'intent.json')),['schemaVersion','kind','cohortDigest','proposalDigest','sandboxDigest','startedAt'])as unknown as MeasurementIntent,evidence=exact(await readPrivateJson(join(directory,'measurement-evidence.json')),['schemaVersion','kind','visibility','pricing','samples'])as unknown as MeasurementEvidence,receipt=exact(await readPrivateJson(join(directory,'measurement-receipt.json')),['schemaVersion','kind','intentDigest','evidenceDigest','measurementDigest']);
 if(intent.schemaVersion!==1||intent.kind!=='measurement-intent'||!Number.isFinite(Date.parse(intent.startedAt))||Date.parse(intent.startedAt)<Date.parse(cohort.recordedAt)||intent.cohortDigest!==jsonDigest(cohort)||intent.proposalDigest!==jsonDigest(context.proposal)||intent.sandboxDigest!==jsonDigest(pair.sandbox)||jsonDigest(pair.context.proposal)!==jsonDigest(context.proposal)||evidence.schemaVersion!==1||evidence.kind!=='measurement-evidence'||receipt.schemaVersion!==1||receipt.kind!=='measurement-receipt'||receipt.intentDigest!==jsonDigest(intent)||receipt.evidenceDigest!==jsonDigest(evidence)||receipt.measurementDigest!==jsonDigest(measurement))throw new Error('measurement-receipt-drift');
 const comparison:ComparisonInputs={input:context.input,proposal:context.proposal,sandbox:pair.sandbox,cohort,samples:evidence.samples,visibility:evidence.visibility,pricing:evidence.pricing};assertMeasuredEvidence(comparison,measurement);return{context,pair,cohort,comparison,measurement,intent,evidence};
}
