import {describe,it,expect} from 'vitest';
import {join} from 'node:path';
import {writeFile,unlink} from 'node:fs/promises';
import {publicationFixture} from './publish.test-helper.js';
import {runPublish,reconcilePublication} from './publish.js';
import {readPrivateJson} from './store.js';

// Fixtures run the actual collect/diagnose/propose/verify/measure/report chain with real Git and private stores.
describe('publication transport and durable reconciliation',{timeout:30000},()=>{
 it('emits exactly one POST, reads back one unmerged PR and repeats with GET only',async()=>{const f=await publicationFixture();const first=await runPublish(f.reportPath,f.permit,f.options);expect(first.status).toBe('published');expect(first.url).toBe(`https://github.com/${f.permit.repository}/pull/1`);expect(f.posts).toHaveLength(1);expect((await runPublish(f.reportPath,f.permit,f.options)).status).toBe('published');expect(f.posts).toHaveLength(1);expect((await readPrivateJson(join(f.publication,'publication-readback.json'))as {merged:boolean}).merged).toBe(false);});
 it('reconciles a successful POST whose response was lost without another POST',async()=>{const f=await publicationFixture();const options={...f.options,mutationRunner:async(...args:Parameters<typeof f.mutationRunner>)=>{await f.mutationRunner(...args);throw new Error('owned response lost');}};expect((await runPublish(f.reportPath,f.permit,options)).status).toBe('published');expect((await reconcilePublication(f.publication,f.options)).status).toBe('published');expect(f.posts).toHaveLength(1);});
 it('retains unknown outcome and performs read-only later recovery',async()=>{const f=await publicationFixture();const options={...f.options,mutationRunner:async(...args:Parameters<typeof f.mutationRunner>)=>{await f.mutationRunner(...args);f.pulls.length=0;throw new Error('owned response lost');}};expect((await runPublish(f.reportPath,f.permit,options)).status).toBe('outcome-unknown');expect((await runPublish(f.reportPath,f.permit,f.options)).status).toBe('outcome-unknown');expect(f.posts).toHaveLength(1);f.pulls.push(f.pull());expect((await reconcilePublication(f.publication,f.options)).status).toBe('published');expect(f.posts).toHaveLength(1);});
 it('keeps unresolved prior POST unknown when a later read-only lookup fails',async()=>{const f=await publicationFixture();const mutationRunner:typeof f.mutationRunner=async(...args)=>{await f.mutationRunner(...args);f.pulls.length=0;throw new Error('owned response lost');};expect((await runPublish(f.reportPath,f.permit,{...f.options,mutationRunner})).status).toBe('outcome-unknown');const pageRunner:typeof f.pageRunner=async(...args)=>{if(args[1].some(arg=>arg.includes('/pulls?')))throw new Error('owned GET unavailable');return f.pageRunner(...args);};expect((await reconcilePublication(f.publication,{...f.options,pageRunner})).status).toBe('outcome-unknown');expect(f.posts).toHaveLength(1);});
 it('does not emit a POST when the permit expires during source readback',async()=>{const f=await publicationFixture();let current=Date.parse('2026-09-30T00:00:00Z');const pageRunner:typeof f.pageRunner=async(...args)=>{const result=await f.pageRunner(...args);if(args[1].some(arg=>arg.includes('/compare/')))current=Date.parse(f.permit.expiresAt);return result;};expect((await runPublish(f.reportPath,f.permit,{...f.options,pageRunner,now:()=>current})).status).toBe('rejected');expect(f.posts).toEqual([]);});
 it('rejects an expired permit before journaling an existing matching PR',async()=>{const f=await publicationFixture();f.pulls.push(f.pull());let current=Date.parse('2026-09-30T00:00:00Z');const pageRunner:typeof f.pageRunner=async(...args)=>{const result=await f.pageRunner(...args);if(args[1].some(arg=>arg.includes('/compare/')))current=Date.parse(f.permit.expiresAt);return result;};const result=await runPublish(f.reportPath,f.permit,{...f.options,pageRunner,now:()=>current});expect(result.status).toBe('rejected');expect(result.reasonCode).toBe('publication-permit-invalid');expect(f.posts).toEqual([]);await expect(readPrivateJson(join(f.publication,'intent.json'))).rejects.toMatchObject({code:'ENOENT'});});
 it('uses the validated operation timestamp for an existing PR journal at the expiry boundary',async()=>{const f=await publicationFixture();f.pulls.push(f.pull());let ticks=0;const now=()=>Date.parse(f.permit.expiresAt)-(ticks++<2?1:0);expect((await runPublish(f.reportPath,f.permit,{...f.options,now})).status).toBe('published');expect((await reconcilePublication(f.publication,f.options)).status).toBe('published');expect(f.posts).toEqual([]);});
 it.each(['missing-permit','ref-drift','marker-conflict','duplicate-marker','merged'])('does not emit on %s',async mutation=>{const f=await publicationFixture();let permit:unknown=f.permit;if(mutation==='missing-permit')permit={};if(mutation==='ref-drift')f.refs.set(f.permit.headRef,'f'.repeat(40));if(mutation==='marker-conflict')f.pulls.push({...f.pull(),body:f.report.marker});if(mutation==='duplicate-marker')f.pulls.push(f.pull(),{...f.pull(),number:2});if(mutation==='merged')f.pulls.push({...f.pull(),merged:true});const result=await runPublish(f.reportPath,permit,f.options);expect(result.status).toBe('rejected');expect(result.reasonCode).toBe(mutation==='missing-permit'?'publication-proof-or-permit-rejected':mutation==='ref-drift'?'publication-ref-drift':'publication-marker-conflict');expect(f.posts).toEqual([]);});
 it('rejects a missing existing intent companion without a second POST',async()=>{const f=await publicationFixture();await runPublish(f.reportPath,f.permit,f.options);await unlink(join(f.publication,'publication-permit.json'));expect((await runPublish(f.reportPath,f.permit,f.options)).status).toBe('rejected');expect(f.posts).toHaveLength(1);});
 it('rejects a altered publication readback before any external read',async()=>{const f=await publicationFixture();await runPublish(f.reportPath,f.permit,f.options);const readback=await readPrivateJson(join(f.publication,'publication-readback.json'))as Record<string,unknown>;readback.merged=true;await writeFile(join(f.publication,'publication-readback.json'),JSON.stringify(readback));const previous=f.calls.length;expect((await reconcilePublication(f.publication,f.options)).status).toBe('rejected');expect(f.calls).toHaveLength(previous);expect(f.posts).toHaveLength(1);});
});
