import {execFile} from 'node:child_process';
import {dirname,join,isAbsolute,resolve} from 'node:path';
import {canonicalJson,decodeArtifact,jsonDigest,sha256,gitBlobSha,type ReportArtifact,type PublicationArtifact} from '@cirujano/core';
import {array,record,positiveInteger} from '../github-api.js';
import {githubGet,githubReadJson,readGitHubSource,type GitHubReadOptions} from './github-read.js';
import {readReportContext,type ReportContext} from './report-service.js';
import {consumePermit,readPrivateJson,readOptimizationArtifact,withOperationStore,type OperationStore} from './store.js';
export interface PublicationPermit{schemaVersion:1;kind:'publication-permit';permitId:string;repositoryId:number;repository:string;baseRef:string;headRef:string;baseSha:string;headSha:string;proposalDigest:string;sandboxDigest:string;measurementDigest:string;reportDigest:string;bodyHash:string;marker:string;expiresAt:string;maxCreates:1}
export type GitHubMutationRunner=(command:string,args:string[],options:{encoding:'utf8';maxBuffer:number;timeout:number;input:string})=>Promise<{stdout:string}>;
export interface PublicationOptions extends GitHubReadOptions{mutationRunner?:GitHubMutationRunner;now?:()=>number;permitLedger?:string;requestTimeoutMs?:number}
export interface PublicationDisposition{status:'published'|'outcome-unknown'|'rejected';reasonCode:string;artifactPath:string|null;url?:string}
interface PublicationIntent{schemaVersion:1;kind:'publication-intent';permitDigest:string;reportDigest:string;reportPath:string;requestHash:string;status:'intent'|'published'|'outcome-unknown'|'rejected';startedAt:string;latestArtifact:string|null;artifactDigest:string|null}
function knownPublicationReason(error:unknown):string|null{return error instanceof Error&&/^publication-(?:ref-drift|marker-conflict|permit-invalid)$/.test(error.message)?error.message:null;}
function exact(value:unknown,keys:string[]){canonicalJson(value);if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join(',')!==[...keys].sort().join(','))throw new Error('publication-companion-invalid');return value as Record<string,unknown>;}
function ref(value:string):string{if(typeof value!=='string'||! /^[A-Za-z0-9][A-Za-z0-9._/-]{0,199}$/.test(value)||value.includes('..')||value.includes('//')||value.endsWith('/')||value.endsWith('.lock'))throw new Error('publication-ref-invalid');return value;}
export function decodePublicationPermit(value:unknown,report:ReportArtifact,now=Date.now()):PublicationPermit{
 decodeArtifact('report',report);const p=exact(value,['schemaVersion','kind','permitId','repositoryId','repository','baseRef','headRef','baseSha','headSha','proposalDigest','sandboxDigest','measurementDigest','reportDigest','bodyHash','marker','expiresAt','maxCreates'])as unknown as PublicationPermit;
 if(report.status!=='ready-to-publish'||p.schemaVersion!==1||p.kind!=='publication-permit'||typeof p.permitId!=='string'||! /^[A-Za-z0-9_-]{1,128}$/.test(p.permitId)||p.repositoryId!==report.provenance.repositoryId||p.repository!==report.provenance.repository||p.baseRef!==report.baseRef||p.headRef!==report.headRef||p.baseRef===p.headRef||p.baseSha!==report.provenance.baseSha||p.headSha!==report.candidateSha||p.proposalDigest!==report.proposalDigest||p.sandboxDigest!==report.sandboxDigest||p.measurementDigest!==report.measurementDigest||p.reportDigest!==jsonDigest(report)||p.bodyHash!==report.markdownHash||p.marker!==report.marker||report.marker!==`<!-- cirujano-optimization:${report.proposalDigest}:${report.measurementDigest} -->`||p.maxCreates!==1||typeof p.expiresAt!=='string'||! /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ$/.test(p.expiresAt)||!Number.isFinite(Date.parse(p.expiresAt))||new Date(p.expiresAt).toISOString().replace('.000Z','Z')!==p.expiresAt||Date.parse(p.expiresAt)<=now)throw new Error('publication-permit-invalid');ref(p.baseRef);ref(p.headRef);return p;
}
function requestFor(report:ReportArtifact){return{title:'Enable verified pnpm store caching',head:report.headRef,base:report.baseRef,body:report.markdown,maintainer_can_modify:false,draft:false};}
async function refsReadback(permit:PublicationPermit,options:PublicationOptions):Promise<void>{
 for(const [name,sha]of [[permit.baseRef,permit.baseSha],[permit.headRef,permit.headSha]]){const response=await githubGet(`repos/${permit.repository}/git/ref/heads/${name!.split('/').map(encodeURIComponent).join('/')}`,options),object=record(response.object,'ref object');if(response.ref!==`refs/heads/${name}`||object.type!=='commit'||object.sha!==sha)throw new Error('publication-ref-drift');}
}
async function publicationSource(report:ReportContext,permit:PublicationPermit,options:PublicationOptions):Promise<void>{
 await refsReadback(permit,options);const repo=await githubGet(`repos/${permit.repository}`,options);if(repo.id!==permit.repositoryId||repo.full_name!==permit.repository||typeof repo.private!=='boolean'||(repo.private?'private':'public')!==report.evidence.visibility)throw new Error('publication-repository-drift');
 for(const [sha,candidate]of [[permit.baseSha,false],[permit.headSha,true]]as const){const actual=await readGitHubSource(permit.repository,sha,options),expected=report.context.source.files.map(file=>candidate&&file.path===report.context.proposal.provenance.workflowPath?{...file,hash:sha256(report.context.candidate),bytesBase64:Buffer.from(report.context.candidate).toString('base64')}:file);if(actual.repositoryId!==permit.repositoryId||canonicalJson(actual.files)!==canonicalJson(expected))throw new Error('publication-source-drift');}
 const comparison=await githubGet(`repos/${permit.repository}/compare/${permit.baseSha}...${permit.headSha}`,options),files=array(comparison.files,'compare files').map(file=>record(file,'compare file'));if(comparison.status!=='ahead'||record(comparison.base_commit,'compare base').sha!==permit.baseSha||record(comparison.merge_base_commit,'merge base').sha!==permit.baseSha||files.length!==1||files[0]!.filename!==report.context.proposal.provenance.workflowPath||files[0]!.status!=='modified'||files[0]!.sha!==gitBlobSha(report.context.candidate))throw new Error('publication-diff-drift');
}
function validPull(raw:unknown,permit:PublicationPermit,report:ReportArtifact):Record<string,unknown>{
 const pull=record(raw,'pull readback'),base=record(pull.base,'pull base'),head=record(pull.head,'pull head'),baseRepo=record(base.repo,'base repo'),headRepo=record(head.repo,'head repo'),number=positiveInteger(pull.number,'pull number');
 if(pull.state!=='open'||pull.merged!==false||pull.merged_at!==null||pull.html_url!==`https://github.com/${permit.repository}/pull/${number}`||base.ref!==permit.baseRef||head.ref!==permit.headRef||base.sha!==permit.baseSha||head.sha!==permit.headSha||baseRepo.id!==permit.repositoryId||headRepo.id!==permit.repositoryId||baseRepo.full_name!==permit.repository||headRepo.full_name!==permit.repository||typeof pull.body!=='string'||pull.body!==report.markdown||sha256(pull.body)!==permit.bodyHash||pull.body.split(permit.marker).length!==2||pull.auto_merge!==null)throw new Error('publication-marker-conflict');return pull;
}
async function lookup(permit:PublicationPermit,report:ReportArtifact,options:PublicationOptions):Promise<Record<string,unknown>|null>{
 const matches:Record<string,unknown>[]=[];let complete=false;
 for(let page=1;page<=50;page++){const rows=array(await githubReadJson(`repos/${permit.repository}/pulls?state=all&per_page=100&page=${page}`,options),'pull list').map(item=>record(item,'pull'));if(rows.length>100)throw new Error('publication-list-size');for(const row of rows)if(typeof row.body==='string'&&row.body.includes(permit.marker))matches.push(row);if(rows.length<100){complete=true;break;}}
 if(!complete||matches.length>1)throw new Error('publication-marker-conflict');if(matches.length===0)return null;const number=positiveInteger(matches[0]!.number,'matched pull number');return validPull(await githubGet(`repos/${permit.repository}/pulls/${number}`,options),permit,report);
}
const defaultMutation:GitHubMutationRunner=(command,args,options)=>new Promise((resolve,reject)=>{const child=execFile(command,args,{encoding:options.encoding,maxBuffer:options.maxBuffer,timeout:options.timeout},(error,stdout)=>error?reject(new Error('publication-write-outcome-unknown')):resolve({stdout}));child.stdin?.end(options.input);});
async function createPull(report:ReportArtifact,permit:PublicationPermit,options:PublicationOptions):Promise<void>{
 decodePublicationPermit(permit,report,(options.now??Date.now)());
 const milliseconds=Math.min(options.requestTimeoutMs??60000,60000);if(!Number.isSafeInteger(milliseconds)||milliseconds<1)throw new Error('publication-deadline-invalid');let timer:ReturnType<typeof setTimeout>|undefined;
 try{await Promise.race([(options.mutationRunner??defaultMutation)(options.ghPath??process.env['CIRUJANO_GH_PATH']??'gh',['api','--method','POST','--hostname','github.com',`repos/${permit.repository}/pulls`,'--input','-','-H','Accept: application/vnd.github+json','-H','X-GitHub-Api-Version: 2022-11-28'],{encoding:'utf8',maxBuffer:1024*1024,timeout:milliseconds,input:canonicalJson(requestFor(report))}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('publication-write-outcome-unknown')),milliseconds);})]);}finally{if(timer)clearTimeout(timer);}
}
function artifactFor(permit:PublicationPermit,report:ReportArtifact,status:PublicationArtifact['status'],pull:Record<string,unknown>|null):PublicationArtifact{return decodeArtifact('publication',{schemaVersion:1,kind:'publication',provenance:report.provenance,candidateSha:report.candidateSha,patchHash:report.patchHash,reportHash:jsonDigest(report),authorizationDigest:jsonDigest(permit),repository:permit.repository,baseRef:permit.baseRef,headRef:permit.headRef,baseSha:permit.baseSha,headSha:permit.headSha,marker:permit.marker,status,number:pull?pull.number:null,url:pull?pull.html_url:null});}
async function finish(store:OperationStore,intent:PublicationIntent,permit:PublicationPermit,report:ReportArtifact,pull:Record<string,unknown>|null,initial:boolean):Promise<PublicationDisposition>{
 const artifact=artifactFor(permit,report,pull?'published':'outcome-unknown',pull),name=initial?'publication.json':`publication-${jsonDigest(artifact)}.json`;try{await store.writeJson(name,artifact);}catch(error){if(!(error instanceof Error&&error.message.startsWith('artifact-exists'))||canonicalJson(await readPrivateJson(join(store.directory,name)))!==canonicalJson(artifact))throw error;}
 if(pull){const readback=publicationReadback(permit,pull);try{await store.writeJson('publication-readback.json',readback);}catch(error){if(!(error instanceof Error&&error.message.startsWith('artifact-exists'))||canonicalJson(await readPrivateJson(join(store.directory,'publication-readback.json')))!==canonicalJson(readback))throw error;}}
 intent.status=artifact.status;intent.latestArtifact=name;intent.artifactDigest=jsonDigest(artifact);await store.writeJson('intent.json',intent,{replaceIntent:true});return{status:artifact.status,reasonCode:pull?'publication-confirmed-unmerged':'publication-outcome-unresolved',artifactPath:join(store.directory,name),...(pull?{url:String(pull.html_url)}:{})};
}
function publicationReadback(permit:PublicationPermit,pull:Record<string,unknown>){return{schemaVersion:1,kind:'publication-readback',number:pull.number,url:pull.html_url,baseRef:permit.baseRef,headRef:permit.headRef,baseSha:permit.baseSha,headSha:permit.headSha,bodyHash:permit.bodyHash,marker:permit.marker,state:'open',merged:false,autoMerge:false};}
async function readIntent(directory:string):Promise<{intent:PublicationIntent;permit:PublicationPermit;reviewed:ReportContext}>{
 const intent=exact(await readPrivateJson(join(directory,'intent.json')),['schemaVersion','kind','permitDigest','reportDigest','reportPath','requestHash','status','startedAt','latestArtifact','artifactDigest'])as unknown as PublicationIntent;
 if(intent.schemaVersion!==1||intent.kind!=='publication-intent'||typeof intent.reportPath!=='string'||!isAbsolute(intent.reportPath)||!Number.isFinite(Date.parse(intent.startedAt))||!['intent','published','outcome-unknown'].includes(intent.status))throw new Error('publication-intent-invalid');
 const reviewed=await readReportContext(intent.reportPath),permit=decodePublicationPermit(await readPrivateJson(join(directory,'publication-permit.json')),reviewed.report,0);
 if(intent.permitDigest!==jsonDigest(permit)||intent.reportDigest!==jsonDigest(reviewed.report)||intent.requestHash!==jsonDigest(requestFor(reviewed.report))||Date.parse(intent.startedAt)>=Date.parse(permit.expiresAt))throw new Error('publication-intent-drift');
 if(intent.latestArtifact===null){if(intent.artifactDigest!==null||intent.status!=='intent')throw new Error('publication-intent-incomplete');}
 else{
  if(typeof intent.latestArtifact!=='string'||! /^(?:publication|publication-[a-f0-9]{64})\.json$/.test(intent.latestArtifact))throw new Error('publication-artifact-name');
  const artifact=await readOptimizationArtifact('publication',join(directory,intent.latestArtifact)),pull=artifact.status==='published'?{number:artifact.number,html_url:artifact.url}:null;
  if(jsonDigest(artifact)!==intent.artifactDigest||artifact.status!==intent.status||canonicalJson(artifact)!==canonicalJson(artifactFor(permit,reviewed.report,artifact.status,pull))||(intent.latestArtifact!=='publication.json'&&intent.latestArtifact!==`publication-${jsonDigest(artifact)}.json`))throw new Error('publication-artifact-drift');
  if(pull&&canonicalJson(await readPrivateJson(join(directory,'publication-readback.json')))!==canonicalJson(publicationReadback(permit,pull)))throw new Error('publication-readback-drift');
 }
 return{intent,permit,reviewed};
}
export async function reconcilePublication(directory:string,options:PublicationOptions={}):Promise<PublicationDisposition>{
 let unresolved=false;
 try{return await withOperationStore(directory,async store=>{const{intent,permit,reviewed}=await readIntent(store.directory);unresolved=intent.status!=='published';await refsReadback(permit,options);const pull=await lookup(permit,reviewed.report,options);return finish(store,intent,permit,reviewed.report,pull,false);});}catch(error){const knownReason=knownPublicationReason(error);return{status:unresolved&&!knownReason?'outcome-unknown':'rejected',reasonCode:knownReason??(unresolved?'publication-outcome-unresolved':'publication-reconciliation-rejected'),artifactPath:null};}
}
export async function runPublish(reportPath:string,permitRaw:unknown,options:PublicationOptions={}):Promise<PublicationDisposition>{
 let reviewed:ReportContext,permit:PublicationPermit;try{reviewed=await readReportContext(reportPath);permit=decodePublicationPermit(permitRaw,reviewed.report,(options.now??Date.now)());}catch{return{status:'rejected',reasonCode:'publication-proof-or-permit-rejected',artifactPath:null};}
 const directory=join(dirname(resolve(reportPath)),'publication');let effectCouldHaveOccurred=false;
 try{return await withOperationStore(directory,async store=>{
  let priorExists=false;try{await readPrivateJson(join(directory,'intent.json'));priorExists=true;}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error;}
  if(priorExists){const prior=await readIntent(directory);if(prior.intent.permitDigest!==jsonDigest(permit))throw new Error('publication-renewal-requires-reconciliation');effectCouldHaveOccurred=prior.intent.status!=='published';await refsReadback(permit,options);return finish(store,prior.intent,permit,reviewed.report,await lookup(permit,reviewed.report,options),false);}
  await publicationSource(reviewed,permit,options);const existing=await lookup(permit,reviewed.report,options),startedAtMs=(options.now??Date.now)();decodePublicationPermit(permit,reviewed.report,startedAtMs);const intent:PublicationIntent={schemaVersion:1,kind:'publication-intent',permitDigest:jsonDigest(permit),reportDigest:jsonDigest(reviewed.report),reportPath:resolve(reportPath),requestHash:jsonDigest(requestFor(reviewed.report)),status:'intent',startedAt:new Date(startedAtMs).toISOString(),latestArtifact:null,artifactDigest:null};await store.writeJson('publication-permit.json',permit);await store.writeJson('intent.json',intent);
  if(existing)return finish(store,intent,permit,reviewed.report,existing,true);
  await refsReadback(permit,options);decodePublicationPermit(permit,reviewed.report,(options.now??Date.now)());await consumePermit({kind:'publication',digest:jsonDigest(permit),operation:intent.requestHash,maximum:1,...(options.permitLedger?{ledger:options.permitLedger}:{})});
  decodePublicationPermit(permit,reviewed.report,(options.now??Date.now)());effectCouldHaveOccurred=true;
  try{await createPull(reviewed.report,permit,options);}catch{/* A sent POST may have succeeded; reconciliation is read-only. */}
  let pull:Record<string,unknown>|null=null;try{pull=await lookup(permit,reviewed.report,options);}catch{/* Never create again after an uncertain readback. */}return finish(store,intent,permit,reviewed.report,pull,true);
 });}catch(error){return{status:effectCouldHaveOccurred?'outcome-unknown':'rejected',reasonCode:effectCouldHaveOccurred?'publication-outcome-unresolved':knownPublicationReason(error)??'publication-stage-rejected',artifactPath:null};}
}
