import {describe,it,expect} from 'vitest';
import {jsonDigest,sha256,type ReportArtifact} from '@cirujano/core';
import {decodePublicationPermit} from './publish.js';
const report={schemaVersion:1,kind:'report',provenance:{repositoryId:123,repository:'owned/proof',baseSha:'1'.repeat(40),workflowBlobSha:'2'.repeat(40),workflowPath:'.github/workflows/ci.yml',workflowHash:'3'.repeat(64),jobId:'test',stepIndex:2,lockfileHash:'4'.repeat(64),sourceTreeDigest:'5'.repeat(64),verificationProfileHash:'6'.repeat(64),toolSourceSha:'7'.repeat(40),bundleDigest:'8'.repeat(64)},candidateSha:'9'.repeat(40),patchHash:'a'.repeat(64),proposalDigest:'b'.repeat(64),sandboxDigest:'c'.repeat(64),measurementDigest:'d'.repeat(64),status:'ready-to-publish',markdown:'owned public reviewed body',markdownHash:sha256('owned public reviewed body'),marker:`<!-- cirujano-optimization:${'b'.repeat(64)}:${'d'.repeat(64)} -->`,baseRef:'main',headRef:'develop'}as ReportArtifact;
const permit=()=>({schemaVersion:1,kind:'publication-permit',permitId:'owned-one-create',repositoryId:report.provenance.repositoryId,repository:report.provenance.repository,baseRef:report.baseRef,headRef:report.headRef,baseSha:report.provenance.baseSha,headSha:report.candidateSha,proposalDigest:report.proposalDigest,sandboxDigest:report.sandboxDigest,measurementDigest:report.measurementDigest,reportDigest:jsonDigest(report),bodyHash:report.markdownHash,marker:report.marker,expiresAt:'2099-09-29T23:00:00Z',maxCreates:1});
describe('exact publication authority',()=>{
 it('binds one exact reviewed body, evidence and existing refs',()=>expect(decodePublicationPermit(permit(),report,Date.parse('2026-09-30T00:00:00Z')).maxCreates).toBe(1));
 it.each(['missing','repo','base','head','sha','report','body','proof','expiry','max','extra'])('rejects authority mutant %s',mutation=>{const changed=permit()as unknown as Record<string,unknown>;if(mutation==='missing')delete changed.permitId;else if(mutation==='repo')changed.repository='other/repo';else if(mutation==='base')changed.baseRef='other';else if(mutation==='head')changed.headRef='working-branch';else if(mutation==='sha')changed.headSha='0'.repeat(40);else if(mutation==='report')changed.reportDigest='0'.repeat(64);else if(mutation==='body')changed.bodyHash='0'.repeat(64);else if(mutation==='proof')changed.measurementDigest='0'.repeat(64);else if(mutation==='expiry')changed.expiresAt='2026-09-29T00:00:00Z';else if(mutation==='max')changed.maxCreates=2;else changed.extra=true;expect(()=>decodePublicationPermit(changed,report,Date.parse('2026-09-30T00:00:00Z'))).toThrow();});
});
