import { describe,it,expect } from 'vitest';
import { jsonDigest } from '@cirujano/core';
import { decodeQualityRun,observeCacheLog,selectedCacheLog,readHostedRunnerIdentity } from './quality-run.js';
const envelope={schemaVersion:1,kind:'github-quality',repositoryId:1,repository:'owned/proof',runId:10,attempt:1,headSha:'1'.repeat(40),workflowPath:'.github/workflows/ci.yml',workflowHash:'2'.repeat(64),jobId:'test',sourceTreeDigest:'3'.repeat(64),lockfileHash:'4'.repeat(64),profileHash:'5'.repeat(64),toolSourceSha:'6'.repeat(40),bundleDigest:'7'.repeat(64),runnerOs:'Linux',runnerArchitecture:'X64',runnerImage:'ubuntu24/20260920.1',nodeVersion:'22.20.0',pnpmVersion:'10.11.0',workflowContractDigest:'8'.repeat(64),quality:{commandDigest:jsonDigest([['pnpm','test']]),tests:[{id:'owned',outcome:'passed'}],coverage:[{path:'src/owned.ts',statements:1,coveredStatements:1,branches:0,coveredBranches:0,functions:1,coveredFunctions:1,lines:1,coveredLines:1}]}};
describe('normalized GitHub quality identity',()=>{
 it('decodes the complete exact typed envelope',()=>expect(decodeQualityRun(envelope)).toEqual(envelope));
 it.each(['extra','sha','attempt','path','image','quality'])('rejects malformed %s',mutation=>{const changed=structuredClone(envelope)as unknown as Record<string,unknown>;if(mutation==='extra')changed.extra=true;else if(mutation==='sha')changed.headSha='main';else if(mutation==='attempt')changed.attempt=0;else if(mutation==='path')changed.workflowPath='../ci.yml';else if(mutation==='image')changed.runnerImage='';else changed.quality={};expect(()=>decodeQualityRun(changed)).toThrow();});
 it('excludes fake cache messages from an intervening action',()=>{const commit='820762786026740c76f36085b0efc47a31fe5020',log=`##[group]Run actions/setup-node@${commit}\nversion v22.20.0\n##[group]Run owned/intervening@${'a'.repeat(40)}\npnpm cache is not found\n##[group]Run pnpm install --frozen-lockfile\n`;expect(observeCacheLog(selectedCacheLog(log,commit),true)).toBe('unknown');});
 it('observes only complete setup-node cache messages',()=>{expect(observeCacheLog('2026-09-29T00:00:00Z pnpm cache is not found\n',true)).toBe('cold');expect(observeCacheLog('2026-09-29T00:00:00Z pnpm cache is not found\n',false)).toBe('miss');expect(observeCacheLog('2026-09-29T00:00:00Z Cache restored from key: node-cache-Linux-x64-pnpm-'+'a'.repeat(64)+'\n',false)).toBe('hit');expect(observeCacheLog('2026-09-29T00:00:00Z echoed fake pnpm cache is not found\n',true)).toBe('unknown');expect(observeCacheLog('pnpm cache is not found\nCache restored from key: node-cache-Linux-x64-pnpm-'+ 'a'.repeat(64)+'\n',true)).toBe('unknown');});
});

describe('provider setup-job runner evidence',()=>{
 const log="Current runner version: '2.329.0'\n##[group]Runner Image\nImage: ubuntu-24.04\nVersion: 20260920.1\nImage Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20260920.1\n##[endgroup]\n##[group]Run actions/checkout@sha\n";
 it('binds the actual selected hosted runner label and setup image',()=>expect(readHostedRunnerIdentity(log,['ubuntu-24.04'],'ubuntu-24.04')).toEqual({runnerOs:'Linux',runnerArchitecture:'X64',runnerImage:'ubuntu24/20260920.1'}));
 it.each(['label','self-hosted','image','version','missing','duplicate','forged'])('rejects %s runner metadata drift',mutation=>{let changed=log,labels=['ubuntu-24.04'];if(mutation==='label')labels=['windows-latest'];else if(mutation==='self-hosted')labels.push('self-hosted');else if(mutation==='image')changed=log.replace('Image: ubuntu-24.04','Image: macos-14');else if(mutation==='version')changed=log.replace('Version: 20260920.1','Version: unknown');else if(mutation==='missing')changed=log.replace('##[group]Runner Image','##[group]Other');else if(mutation==='duplicate')changed=log.replace('##[group]Run actions/checkout@sha',log);else changed='Current runner version: 2.329.0\n##[group]Run node untrusted\n'+log;expect(()=>readHostedRunnerIdentity(changed,labels,'ubuntu-24.04')).toThrow();});
});

describe('selected cache step boundaries',()=>{
 const commit='820762786026740c76f36085b0efc47a31fe5020',setup=`##[group]Run actions/setup-node@${commit}`,install='##[group]Run pnpm install --frozen-lockfile';
 it('keeps only timestamped setup-node output',()=>{const log=[setup,'pnpm cache is not found',install,'pnpm cache is not found'].map(line=>`2026-09-29T00:00:00.1234567Z ${line}`).join('\r\n');expect(observeCacheLog(selectedCacheLog(log,commit),true)).toBe('cold');});
 it.each(['duplicate-setup','duplicate-install','install-before-setup','missing-install','missing-setup'])('rejects ambiguous boundaries: %s',mutation=>{let lines=[setup,'pnpm cache is not found',install];if(mutation==='duplicate-setup')lines.unshift(setup);else if(mutation==='duplicate-install')lines.push(install);else if(mutation==='install-before-setup')lines=[install,setup,'pnpm cache is not found'];else if(mutation==='missing-install')lines.pop();else lines.shift();expect(selectedCacheLog(lines.join('\n'),commit)).toBe('');});
});
