import {dirname,join,basename} from 'node:path';
import {canonicalJson,jsonDigest,renderOptimizationReport,type ReportArtifact,type ReportRenderInputs} from '@cirujano/core';
import {readProposalContext,copyProposalContext} from './propose.js';
import {readSandboxContext} from './verify.js';
import {readMeasurementContext,retainSandboxEvidence,type MeasurementContext} from './measure.js';
import {readPrivateJson,readPrivateText,readOptimizationArtifact,withOperationStore,type OperationStore} from './store.js';
export interface ReportDisposition{status:'ready-to-publish'|'no-improvement'|'rejected'|'failed';reasonCode:string;artifactPath:string|null}
export interface ReportContext extends MeasurementContext{report:ReportArtifact;render:ReportRenderInputs}
function exact(value:unknown,keys:string[]){canonicalJson(value);if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join(',')!==[...keys].sort().join(','))throw new Error('report-companion-invalid');return value as Record<string,unknown>;}
function renderInputs(measured:MeasurementContext,baseRef:string,headRef:string):ReportRenderInputs{return{...measured.comparison,diagnosis:measured.context.diagnosis,inference:measured.context.inference,measurement:measured.measurement,patch:measured.context.patch,baseRef,headRef};}
export async function retainMeasurementEvidence(store:OperationStore,path:string,measured:MeasurementContext):Promise<void>{
 await withOperationStore(join(store.directory,'measurement-evidence'),async nested=>{await copyProposalContext(nested,measured.context);await retainSandboxEvidence(nested,join(dirname(path),'sandbox-evidence','sandbox.json'),measured.pair);await nested.writeJson('cohort.json',measured.cohort);await nested.writeJson('intent.json',measured.intent);await nested.writeJson('measurement-evidence.json',measured.evidence);await nested.writeArtifact('measurement',measured.measurement);await nested.writeJson('measurement-receipt.json',await readPrivateJson(join(dirname(path),'measurement-receipt.json')));});
}
export async function runReport(proposalPath:string,sandboxPath:string,measurementPath:string,output:string,baseRef='main',headRef='develop'):Promise<ReportDisposition>{
 try{const context=await readProposalContext(proposalPath),pair=await readSandboxContext(sandboxPath),measured=await readMeasurementContext(measurementPath);if(jsonDigest(context.proposal)!==jsonDigest(measured.context.proposal)||jsonDigest(pair.sandbox)!==jsonDigest(measured.pair.sandbox))throw new Error('report-input-drift');const render=renderInputs(measured,baseRef,headRef),report=renderOptimizationReport(render);
  return await withOperationStore(output,async store=>{await copyProposalContext(store,context);await retainMeasurementEvidence(store,measurementPath,measured);await store.writeArtifact('report',report);await store.writeText('report.md',report.markdown);await store.writeJson('report-receipt.json',{schemaVersion:1,kind:'report-receipt',renderDigest:jsonDigest(render),reportDigest:jsonDigest(report),bodyHash:report.markdownHash});await store.writeJson('operation.json',{schemaVersion:1,kind:'optimization-operation',action:'report',status:report.status,reasonCode:report.status,inputDigest:jsonDigest(context.input),nextCommand:'cirujano --help'});return{status:report.status,reasonCode:report.status,artifactPath:join(store.directory,'report.json')};});
 }catch{return{status:'failed',reasonCode:'report-evidence-rejected',artifactPath:null};}
}
export async function readReportContext(path:string):Promise<ReportContext>{
 if(basename(path)!=='report.json')throw new Error('report-filename');const directory=dirname(path),context=await readProposalContext(join(directory,'proposal.json')),measured=await readMeasurementContext(join(directory,'measurement-evidence','measurement.json')),report=await readOptimizationArtifact('report',path),receipt=exact(await readPrivateJson(join(directory,'report-receipt.json')),['schemaVersion','kind','renderDigest','reportDigest','bodyHash']);
 const render=renderInputs(measured,report.baseRef,report.headRef);if(jsonDigest(context.proposal)!==jsonDigest(measured.context.proposal)||canonicalJson(report)!==canonicalJson(renderOptimizationReport(render))||receipt.schemaVersion!==1||receipt.kind!=='report-receipt'||receipt.renderDigest!==jsonDigest(render)||receipt.reportDigest!==jsonDigest(report)||receipt.bodyHash!==report.markdownHash||await readPrivateText(join(directory,'report.md'))!==report.markdown)throw new Error('report-evidence-drift');return{...measured,report,render};
}
