import { execFileSync } from 'node:child_process';
import { readFile,writeFile,mkdir,mkdtemp,realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,dirname } from 'node:path';
import { canonicalJson,jsonDigest,sha256,decodeArtifact,type QualityEvidence } from '@cirujano/core';
import { createOptimizationService } from './service.js';
import { githubFixture,baseSha,repository } from './github-read.test-helper.js';
import { config,permitFixture,responseFixture,model } from './nebius.test-helper.js';
import { readPrivateJson } from './store.js';
import { decodeExecutionProfile,completeCommands,type ExecutionProfile,type SandboxPayload } from './execution-profile.js';
import type { OptimizeArguments } from './arguments.js';
export const optimizationCommand=(action:OptimizeArguments['action'],flags:Record<string,string|string[]>):OptimizeArguments=>({command:'optimize',action,flags,format:'json'});
export async function verificationFixture(options:{singleJob?:boolean}={}){
 const directory=await realpath(await mkdtemp(join(tmpdir(),'optimization-verify-'))),repositoryPath=join(directory,'repository');await mkdir(repositoryPath);
 const fixture=githubFixture();
 if(options.singleJob)for(const response of Object.values(fixture.responses)){if(response&&typeof response==='object'&&'jobs'in response){const page=response as {total_count:number;jobs:{name:string}[]};page.jobs=page.jobs.filter(job=>job.name==='test');page.total_count=page.jobs.length;}else if(response&&typeof response==='object'&&'check_runs'in response){const page=response as {total_count:number;check_runs:{name:string}[]};page.check_runs=page.check_runs.filter(check=>check.name==='test');page.total_count=page.check_runs.length;}}
 const git=(...args:string[])=>execFileSync('git',['-C',repositoryPath,'-c','core.hooksPath=/dev/null','-c','core.fsmonitor=false','-c','user.name=Owned Fixture','-c','user.email=fixture@invalid','-c','commit.gpgsign=false',...args],{encoding:'utf8'}).trim();
 for(const [path,bytes]of Object.entries(fixture.files)){await mkdir(dirname(join(repositoryPath,path)),{recursive:true});await writeFile(join(repositoryPath,path),bytes);}
 git('init','--initial-branch=develop');git('add','.');git('commit','-m','Owned baseline');const realBase=git('rev-parse','HEAD');
 const pageRunner:typeof fixture.pageRunner=async(command,args,options)=>{const reply=await fixture.pageRunner(command,args.map(arg=>arg.replace(realBase,baseSha)),options);const parsed=JSON.parse(reply.stdout);function rewrite(value:unknown):unknown{if(Array.isArray(value))return value.map(rewrite);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,(key==='head_sha'||key==='sha')&&item===baseSha?realBase:rewrite(item)]));return value;}return{stdout:JSON.stringify(rewrite(parsed))};};
 const output:string[]=[],io={stdout:(value:string)=>output.push(value),stderr:(value:string)=>output.push(value)},collected=join(directory,'collected'),diagnosed=join(directory,'diagnosed'),proposed=join(directory,'proposed'),verified=join(directory,'verified');
 const service=createOptimizationService({pageRunner,toolSourceSha:'1'.repeat(40),bundleDigest:'2'.repeat(64),apiKey:'owned-synthetic-inference',permitLedger:join(directory,'inference-ledger'),fetch:async(_url,init)=>init?.method==='GET'?new Response(JSON.stringify({data:[{id:model}]})):new Response(JSON.stringify((()=>{const response=responseFixture(),decision=JSON.parse(response.choices[0]!.message.content);decision.evidenceIds=['install-timing'];response.choices[0]!.message.content=JSON.stringify(decision);return response;})()))});
 if(await service.run(optimizationCommand('collect',{repository,ref:realBase,workflow:'.github/workflows/ci.yml',job:'test',run:['99'],output:collected}),io)!==0)throw new Error(output.join(''));
 const input=decodeArtifact('input',await readPrivateJson(join(collected,'input.json'))),configPath=join(directory,'config.json'),inferencePermit=join(directory,'inference-permit.json');await writeFile(configPath,JSON.stringify(config));await writeFile(inferencePermit,JSON.stringify(permitFixture(input)));
 if(await service.run(optimizationCommand('diagnose',{input:join(collected,'input.json'),config:configPath,permit:inferencePermit,output:diagnosed}),io)!==0)throw new Error(output.join(''));
 if(await service.run(optimizationCommand('propose',{input:join(collected,'input.json'),diagnosis:join(diagnosed,'diagnosis.json'),output:proposed}),io)!==0)throw new Error(output.join(''));
 const proposal=decodeArtifact('proposal',await readPrivateJson(join(proposed,'proposal.json'))),candidate=await readFile(join(proposed,'candidate.yml'),'utf8');await writeFile(join(repositoryPath,'.github/workflows/ci.yml'),candidate);git('add','.');git('commit','-m','Owned exact candidate');const candidateSha=git('rev-parse','HEAD');
 const quality:QualityEvidence={commandDigest:jsonDigest(completeCommands(proposal.verificationProfile)),tests:[{id:'Owned test',outcome:'passed'}],coverage:[{path:'owned.ts',statements:1,coveredStatements:1,branches:0,coveredBranches:0,functions:1,coveredFunctions:1,lines:1,coveredLines:1}]};
 const harnessBytes=await readFile(new URL('../../../../scripts/optimization/harness.mjs',import.meta.url));
 const manifest={schemaVersion:1,kind:'optimization-image',toolSourceSha:input.provenance.toolSourceSha,bundleDigest:input.provenance.bundleDigest,nodeVersion:proposal.verificationProfile.nodeVersion,pnpmVersion:proposal.verificationProfile.pnpmVersion,lockfileHash:input.provenance.lockfileHash,dependencyStoreHash:'7'.repeat(64),harnessHash:sha256(harnessBytes),recipeHash:'8'.repeat(64)},manifestBytes=Buffer.from(canonicalJson(manifest));
 const profile:ExecutionProfile=decodeExecutionProfile({schemaVersion:1,kind:'execution-profile',provenance:input.provenance,proposalDigest:jsonDigest(proposal),candidateSha,candidateRepository:repositoryPath,project:'owned-project',image:{uuid:'12345678-9abc-baba-deda-0123456789ab',ociDigest:'4'.repeat(64),registryReference:'docker://registry.invalid/proof@sha256:'+'4'.repeat(64),importOperationId:'12345678-9abc-baba-deda-0123456789ac',recipeHash:manifest.recipeHash,manifestHash:sha256(manifestBytes),dependencyStoreHash:manifest.dependencyStoreHash,harnessHash:manifest.harnessHash},verificationProfile:proposal.verificationProfile,expectedQuality:quality,timeoutSeconds:600,maxLayerBytes:104857600,imageRetention:'owner-retained'});
 const permit={schemaVersion:1,kind:'sandbox-permit',permitId:'owned-execution',repositoryId:input.provenance.repositoryId,proposalDigest:jsonDigest(proposal),profileDigest:jsonDigest(profile),candidateSha,imageUuid:profile.image.uuid,project:profile.project,expiresAt:'2099-09-29T23:00:00Z',maxOperations:2};const calls:{url:string;method:string;body:unknown}[]=[],payloads=new Map<string,SandboxPayload>(),requests=new Map<string,Record<string,unknown>>();let creates=0;
 const fetcher:typeof fetch=async(url,init)=>{const target=String(url),method=init?.method??'GET',body=init?.body?JSON.parse(String(init.body)):null;calls.push({url:target,method,body});
  if(target.includes('/inspect/')&&target.includes('/download?'))return new Response(target.includes('harness.mjs')?harnessBytes:manifestBytes);
  if(target.includes('/inspect/'))return new Response(JSON.stringify({uuid:profile.image.uuid,operation_uuid:profile.image.importOperationId}));
  if(target.endsWith(profile.image.importOperationId))return new Response(JSON.stringify({uuid:profile.image.importOperationId,kind:'image_import',status:'SUCCESS',result:{image:profile.image.uuid},metadata:{registry:{url:profile.image.registryReference}}}));
  if(method==='POST'){const id=`12345678-9abc-baba-deda-0123456789${++creates===1?'ad':'ae'}`,payload=JSON.parse(Buffer.from(body.stdin.value,'base64').toString('utf8')) as SandboxPayload;payloads.set(id,payload);requests.set(id,body);return new Response(JSON.stringify({uuid:id,image:profile.image.uuid}),{status:201,headers:{Location:`/sandboxes/v1/operations/${id}`}});}
  const id=target.split('/').at(-1)!,payload=payloads.get(id);if(!payload)throw new Error('unowned operation');
  const envelope={schemaVersion:1,kind:'harness-result',role:payload.role,profileDigest:payload.profileDigest,proposalDigest:payload.proposalDigest,toolSourceSha:payload.toolSourceSha,bundleDigest:payload.bundleDigest,imageManifestHash:payload.imageManifestHash,harnessHash:payload.harnessHash,sourceDigest:payload.sourceDigest,workflowHash:payload.workflowHash,commands:completeCommands(payload.verificationProfile).map(argv=>({argv,exitCode:0,signal:null,timedOut:false,truncated:false,stdoutHash:sha256(''),stderrHash:sha256('')})),quality:structuredClone(quality),elapsedMs:10};
  return new Response(JSON.stringify({uuid:id,kind:'instance',status:'SUCCESS',image_uuid:profile.image.uuid,result_image_uuid:null,metadata:{...requests.get(id),result:{state:{exit_code:0,signal:0,timed_out:false,stopped:false,continued:false,core_dump:false},stdout:{value:Buffer.from(canonicalJson(envelope)+'\n').toString('base64'),encoding:'base64',truncated:false},stderr:{value:'',encoding:'ascii',truncated:false},resources:{cost:0.01}}}}));
 };
 return{directory,repositoryPath,git,profile,permit,proposed,verified,proposal,candidate,quality,calls,payloads,fetcher,creates:()=>creates,io,output,harnessBytes,manifestBytes};
}
