import { rm,writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach,describe,expect,it } from 'vitest';
import { decodeArtifact,jsonDigest } from '@cirujano/core';
import { verificationFixture } from './verify.test-helper.js';
import { verifyPair,reconcileSandbox,readSandboxContext,cancelSandbox } from './verify.js';
import { readPrivateJson } from './store.js';
import { createOptimizationService } from './service.js';
import { optimizationCommand } from './verify.test-helper.js';
const directories:string[]=[];
afterEach(async()=>{for(const path of directories.splice(0))await rm(path,{recursive:true,force:true});});
async function setup(){const f=await verificationFixture();directories.push(f.directory);const options={iamToken:'owned-synthetic-IAM-secret',fetch:f.fetcher,permitLedger:join(f.directory,'sandbox-ledger'),deadlineMs:1000,pollIntervalMs:1};const run=(profile:unknown=f.profile,permit:unknown=f.permit,output=f.verified,transport:typeof fetch=f.fetcher)=>verifyPair(join(f.proposed,'proposal.json'),profile,permit,output,{...options,fetch:transport});return{...f,options,run};}
describe('paired Sandbox verification orchestration',()=>{
 it('binds two real candidate/source identities and keeps all credentials out of guest payload/env',async()=>{const f=await setup(),result=await f.run();expect(result.status).toBe('sandbox-verified');expect(f.creates()).toBe(2);const artifact=decodeArtifact('sandbox',await readPrivateJson(join(f.verified,'sandbox.json')));expect(artifact.candidateSha).toBe(f.profile.candidateSha);expect(artifact.retainedImage).toBe(true);expect(artifact.cleanupState).toBe('disposable-confirmed');expect(artifact.usage?.currency).toBeNull();expect(artifact.usage?.unit).toBe('undocumented-provider-unit');expect(JSON.stringify(f.calls.map(call=>call.body))).not.toContain('owned-synthetic-IAM-secret');expect(await readSandboxContext(join(f.verified,'sandbox.json'))).toBeDefined();});
 it('rejects a provisioning recipe without image UUID/readback and emits no create',async()=>{const f=await setup();expect((await f.run({schemaVersion:1,kind:'image-recipe'})).status).toBe('rejected');expect(f.creates()).toBe(0);});
 it('rejects a real candidate with extra changed source before any provider request',async()=>{const f=await setup();await writeFile(join(f.repositoryPath,'package.json'),'{}');f.git('add','.');f.git('commit','-m','Forbidden source drift');const profile={...f.profile,candidateSha:f.git('rev-parse','HEAD')};expect((await f.run(profile,{...f.permit,candidateSha:profile.candidateSha,profileDigest:jsonDigest(profile)})).status).toBe('rejected');expect(f.calls).toHaveLength(0);});
 it('does not replay completed or uncertain stages or reuse exhausted authority in another output',async()=>{const f=await setup();expect((await f.run()).status).toBe('sandbox-verified');expect((await f.run()).status).toBe('outcome-unknown');expect(f.creates()).toBe(2);expect((await f.run(f.profile,f.permit,join(f.directory,'second'))).status).toBe('failed');expect(f.creates()).toBe(2);});
 it('retains a lost create outcome and discloses provider inspection with no additional POST',async()=>{const f=await setup();const transport:typeof fetch=async(url,init)=>{if(init?.method==='POST'){await f.fetcher(url,init);throw Error('lost provider reply');}return f.fetcher(url,init);};const result=await f.run(f.profile,f.permit,f.verified,transport);expect(result.status).toBe('outcome-unknown');expect(result.reasonCode).toContain('provider-inspection-required');expect(result.recovery).toContain('before a new create');expect(f.creates()).toBe(1);expect((await reconcileSandbox(f.verified,f.options)).status).toBe('outcome-unknown');expect(f.creates()).toBe(1);});
 it.each(['deleted-test','skip','coverage','hash','command'])('blocks candidate quality/hash/command mutant %s',async mutation=>{const f=await setup();const transport:typeof fetch=async(url,init)=>{const response=await f.fetcher(url,init);if(init?.method!=='POST'&&String(url).endsWith('ae')){const raw=await response.json() as {metadata:{result:{stdout:{value:string},state:{exit_code:number}}}};const envelope=JSON.parse(Buffer.from(raw.metadata.result.stdout.value,'base64').toString('utf8'));if(mutation==='deleted-test')envelope.quality.tests=[];else if(mutation==='skip')envelope.quality.tests[0].outcome='skipped';else if(mutation==='coverage')envelope.quality.coverage[0].statements=0;else if(mutation==='hash')envelope.sourceDigest='9'.repeat(64);else envelope.commands.pop();raw.metadata.result.stdout.value=Buffer.from(JSON.stringify(envelope)).toString('base64');return new Response(JSON.stringify(raw));}return response;};expect((await f.run(f.profile,f.permit,f.verified,transport)).status).toBe('failed');expect(f.creates()).toBe(2);const artifact=decodeArtifact('sandbox',await readPrivateJson(join(f.verified,'sandbox.json')));expect(artifact.truncated).toBe(false);});
 it('does not start candidate execution after a failed base command',async()=>{const f=await setup();const transport:typeof fetch=async(url,init)=>{const response=await f.fetcher(url,init);if(init?.method!=='POST'&&String(url).endsWith('ad')){const raw=await response.json() as {metadata:{result:{stdout:{value:string},state:{exit_code:number}}}};raw.metadata.result.state.exit_code=1;return new Response(JSON.stringify(raw));}return response;};expect((await f.run(f.profile,f.permit,f.verified,transport)).status).toBe('failed');expect(f.creates()).toBe(1);});
 it('rejects altered retained profile/artifact on readback instead of trusting verified status',async()=>{const f=await setup();expect((await f.run()).status).toBe('sandbox-verified');const sandbox=decodeArtifact('sandbox',await readPrivateJson(join(f.verified,'sandbox.json')));sandbox.patchHash='9'.repeat(64);await writeFile(join(f.verified,'sandbox.json'),JSON.stringify(sandbox));await expect(readSandboxContext(join(f.verified,'sandbox.json'))).rejects.toThrow();});
 it('never cancels an unowned operation or one authorized for another image',async()=>{const f=await setup();expect((await f.run()).status).toBe('sandbox-verified');const result=await cancelSandbox(f.verified,{...f.permit,imageUuid:'12345678-9abc-baba-deda-0123456789ff'},f.options);expect(result.status).toBe('rejected');expect(f.calls.filter(call=>call.method==='DELETE')).toHaveLength(0);});
 it('executes verify and reconciles status through the installed command service',async()=>{const f=await setup(),profile=join(f.directory,'profile.json'),permit=join(f.directory,'execution-permit.json');await writeFile(profile,JSON.stringify(f.profile));await writeFile(permit,JSON.stringify(f.permit));const service=createOptimizationService({iamToken:f.options.iamToken,fetch:f.fetcher,permitLedger:f.options.permitLedger});expect(await service.run(optimizationCommand('verify',{proposal:join(f.proposed,'proposal.json'),profile,permit,output:f.verified}),f.io)).toBe(0);expect(f.output.at(-1)).toContain('sandbox-verified');expect(await service.run(optimizationCommand('status',{operation:f.verified}),f.io)).toBe(0);expect(f.creates()).toBe(2);});
 it.each(['sandbox','image'])('status rejects single-file completed %s evidence tampering',async mutation=>{const f=await setup();expect((await f.run()).status).toBe('sandbox-verified');const path=join(f.verified,mutation==='sandbox'?'sandbox.json':'image-readback.json'),raw=await readPrivateJson(path) as Record<string,unknown>;raw[mutation==='sandbox'?'patchHash':'manifestHash']='9'.repeat(64);await writeFile(path,JSON.stringify(raw));const service=createOptimizationService({iamToken:f.options.iamToken,fetch:f.fetcher});expect(await service.run(optimizationCommand('status',{operation:f.verified}),f.io)).toBe(1);expect(f.output.at(-1)).toContain('rejected');});
 it('checks actual operation ownership before any cancellation DELETE',async()=>{const f=await setup();const transport:typeof fetch=async(url,init)=>{if(init?.method!=='POST'&&String(url).endsWith('ad'))return new Response('',{status:503});return f.fetcher(url,init);};expect((await f.run(f.profile,f.permit,f.verified,transport)).status).toBe('outcome-unknown');f.calls.length=0;const journal=await readPrivateJson(join(f.verified,'intent.json')) as {latestArtifact:string|null;artifactDigest:string|null;roles:{record:{id:string;url:string}|null}[]};journal.latestArtifact=null;journal.artifactDigest=null;journal.roles[0]!.record!.id='12345678-9abc-baba-deda-0123456789ff';journal.roles[0]!.record!.url='https://api.tokenfactory.nebius.com/sandboxes/v1/operations/12345678-9abc-baba-deda-0123456789ff';await writeFile(join(f.verified,'intent.json'),JSON.stringify(journal));expect((await cancelSandbox(f.verified,f.permit,f.options)).status).toBe('rejected');expect(f.calls.filter(call=>call.method==='DELETE')).toHaveLength(0);});
 it('cancels an owned known running operation and confirms terminal disposable state without a second create',async()=>{const f=await setup();let cancelled=false,deletes=0;const transport:typeof fetch=async(url,init)=>{const response=await f.fetcher(url,init);if(init?.method==='POST')return new Response('{malformed',{status:201,headers:response.headers});if(String(url).endsWith('ad')){if(init?.method==='DELETE'){cancelled=true;deletes++;return new Response('',{status:202});}const raw=await response.json() as {status:string};raw.status=cancelled?'CANCELLED':'EXECUTING';return new Response(JSON.stringify(raw));}return response;};expect((await f.run(f.profile,f.permit,f.verified,transport)).status).toBe('outcome-unknown');const result=await cancelSandbox(f.verified,f.permit,{...f.options,fetch:transport});expect(result.status).toBe('failed');expect(deletes).toBe(1);expect(f.creates()).toBe(1);const artifact=decodeArtifact('sandbox',await readPrivateJson(result.artifactPath!));expect(artifact.operations[0]?.status).toBe('CANCELLED');expect(artifact.cleanupState).toBe('disposable-confirmed');expect(artifact.retainedImage).toBe(true);});
});
