import { canonicalJson, OptimizationInputError, safeRelativePath, sha256, gitBlobSha } from './canonical.js';

export type LifecycleStatus = 'collected' | 'diagnosed' | 'proposed' | 'sandbox-verified' | 'measured-improvement' | 'ready-to-publish' | 'published' | 'no-change' | 'unsupported' | 'rejected' | 'no-improvement' | 'failed' | 'outcome-unknown';
export interface Provenance {
  repositoryId: number; repository: string; baseSha: string; workflowBlobSha: string;
  workflowPath: string; workflowHash: string; jobId: string; stepIndex: number; lockfileHash: string;
  sourceTreeDigest: string; verificationProfileHash: string; toolSourceSha: string; bundleDigest: string;
}
export interface CacheOperation { type: 'enable-pnpm-cache'; jobId: string; stepIndex: number }
export interface ActionReceipt { repository: 'actions/setup-node'; commitSha: string; releaseTag: string; releaseId: number; immutable: true; actionHash: string; inputs: string[]; outputs: string[]; retrievedAt: string }
export interface VerificationProfile { schemaVersion: 1; commands: string[][]; testReportPath: string; coverageReportPath: string; nodeVersion: string; pnpmVersion: string; timeoutSeconds: number; sourcePaths: string[] }
export interface TestOutcome { id: string; outcome: 'passed' | 'failed' | 'skipped' }
export interface CoverageCounters { path: string; statements: number; coveredStatements: number; branches: number; coveredBranches: number; functions: number; coveredFunctions: number; lines: number; coveredLines: number }
export interface QualityEvidence { commandDigest: string; tests: TestOutcome[]; coverage: CoverageCounters[] }
export interface BaselineJob { runId: number; attempt: number; jobId: number; headSha: string; conclusion: 'success'; startedAt: string; completedAt: string; elapsedMs: number; installStepNumber: number; installElapsedMs: number; runnerLabels: string[]; runnerImage: string | null; requiredChecks: string[] }
export interface BaseArtifact<K extends string> { schemaVersion: 1; kind: K; provenance: Provenance }
export interface InputArtifact extends BaseArtifact<'input'> { status: 'collected' | 'no-change' | 'unsupported'; baselines: BaselineJob[]; structuralFacts: Record<string, string | number | boolean | null>; evidence: Record<string, string>; operations: CacheOperation[]; requiredChecks: string[] }
export interface DiagnosisArtifact extends BaseArtifact<'diagnosis'> { status: 'proposal' | 'abstain'; reason: string; uncertainty: string; evidenceIds: string[]; operation: CacheOperation | null; promptVersion: string; schemaVersionId: string; inferenceReceiptDigest: string }
export interface InferenceArtifact extends BaseArtifact<'inference'> { requestedModel: string; returnedModel: string | null; endpointHost: string; completionId: string | null; requestHash: string; responseHash: string | null; startedAt: string; completedAt: string; latencyMs: number; finishReason: string | null; usage: { promptTokens: number; completionTokens: number; totalTokens: number } | null; quoteIdentity: string | null; costStatus: 'known' | 'unavailable' | 'unknown'; cost: { amount: number; currency: string } | null; status: 'completed' | 'not-run' | 'failed' | 'outcome-unknown' }
export interface ProposalArtifact extends BaseArtifact<'proposal'> { status: 'proposed' | 'no-change' | 'rejected'; operation: CacheOperation; candidateSha: string | null; candidateWorkflowHash: string; patchHash: string; beforeStructuralDigest: string; afterStructuralDigest: string; permittedDiff: { cache: 'pnpm'; cacheDependencyPath: 'pnpm-lock.yaml' }; preconditions: string[]; verificationProfile: VerificationProfile; diagnosisDigest: string }
export interface SandboxOperation { id: string; status: 'PENDING' | 'ASSIGNED' | 'EXECUTING' | 'SUCCESS' | 'FAILED' | 'CANCELLED'; role: 'base' | 'candidate'; exitCode: number | null; signal: string | null; timedOut: boolean; truncated: boolean }
export interface SandboxArtifact extends BaseArtifact<'sandbox'> { candidateSha: string; patchHash: string; proposalDigest: string; status: 'sandbox-verified' | 'failed' | 'outcome-unknown'; image: { uuid: string; digest: string; recipeHash: string; manifestHash: string }; operations: SandboxOperation[]; networkEnabled: false; baseQuality: QualityEvidence | null; candidateQuality: QualityEvidence | null; startedAt: string; completedAt: string | null; elapsedMs: number | null; usage: { value: number; unit: string; currency: string | null } | null; truncated: boolean; cleanupState: 'disposable-confirmed' | 'pending' | 'unknown'; retainedImage: true }
export interface MeasurementSample { role: 'base' | 'candidate'; runId: number; attempt: number; jobId: number; headSha: string; startedAt: string; completedAt: string; elapsedMs: number; roundedMinutes: number; queueMs: number; endToEndMs: number; conclusion: 'success' | 'failure' | 'cancelled' | 'skipped'; runnerOs: string; runnerArchitecture: string; runnerImage: string; nodeVersion: string; pnpmVersion: string; workflowContractDigest: string; sourceTreeDigest: string; lockfileHash: string; requiredChecks: { name: string; conclusion: string }[]; cacheObservation: 'cold' | 'hit' | 'miss' | 'not-applicable' | 'unknown'; quality: QualityEvidence }
export interface MeasurementArtifact extends BaseArtifact<'measurement'> { candidateSha: string; patchHash: string; proposalDigest: string; sandboxDigest: string; cohortDigest: string; status: 'measured-improvement' | 'no-improvement' | 'rejected'; samples: MeasurementSample[]; baselineMinutes: number; candidateMinutes: number; baselineMedianMs: number; candidateMedianMs: number; maximumQueueMs: number; maximumEndToEndMs: number; limits: string[]; claimLevel: 'sample-execution-only' | 'none'; githubListSavingUsd: number }
export interface PublicationArtifact extends BaseArtifact<'publication'> { candidateSha: string; patchHash: string; reportHash: string; authorizationDigest: string; repository: string; baseRef: string; headRef: string; baseSha: string; headSha: string; marker: string; status: 'published' | 'outcome-unknown' | 'rejected'; number: number | null; url: string | null }
export interface ReportArtifact extends BaseArtifact<'report'> { candidateSha: string; patchHash: string; proposalDigest: string; sandboxDigest: string; measurementDigest: string; status: 'ready-to-publish' | 'no-improvement' | 'rejected'; markdown: string; markdownHash: string; marker: string; baseRef: string; headRef: string }
export interface ArtifactMap { input: InputArtifact; diagnosis: DiagnosisArtifact; inference: InferenceArtifact; proposal: ProposalArtifact; sandbox: SandboxArtifact; measurement: MeasurementArtifact; report: ReportArtifact; publication: PublicationArtifact }
export type ArtifactKind = keyof ArtifactMap;
type Validator = (value: unknown, path: string) => void;
function fail(path: string): never { throw new OptimizationInputError(`Invalid optimization field: ${path}`); }
const text: Validator = (v, p) => { if (typeof v !== 'string' || !v || Buffer.byteLength(v) > 8192 || /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v)) fail(p); };
const number: Validator = (v, p) => { if (typeof v !== 'number' || !Number.isFinite(v) || v < 0) fail(p); };
const sourceBytes: Validator = (v,p) => { if (typeof v !== 'string' || Buffer.byteLength(v)>Math.ceil(4*1024*1024/3)*4 || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(v)) fail(p); };
const integer: Validator = (v, p) => { number(v,p); if (!Number.isSafeInteger(v)) fail(p); };
const id: Validator = (v,p) => { integer(v,p); if (v === 0) fail(p); };
const bool: Validator = (v,p) => { if (typeof v !== 'boolean') fail(p); };
const digest: Validator = (v,p) => { if (typeof v !== 'string' || !/^[a-f0-9]{64}$/.test(v)) fail(p); };
const semver: Validator = (v,p) => { if (typeof v !== 'string' || !/^\d+\.\d+\.\d+$/.test(v)) fail(p); };
const sha: Validator = (v,p) => { if (typeof v !== 'string' || !/^[a-f0-9]{40}$/.test(v)) fail(p); };
const timestamp: Validator = (v,p) => { if (typeof v !== 'string' || !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{3})?Z$/.test(v) || !Number.isFinite(Date.parse(v)) || new Date(v).toISOString().replace('.000Z','Z') !== v.replace('.000Z','Z')) fail(p); };
const path: Validator = (v,p) => { text(v,p); safeRelativePath(v as string); };
const repo: Validator = (v,p) => { if (typeof v !== 'string' || !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(v)) fail(p); };
const literal = (...values: unknown[]): Validator => (v,p) => { if (!values.includes(v)) fail(p); };
const nullable = (validate: Validator): Validator => (v,p) => { if (v !== null) validate(v,p); };
const array = (validate: Validator, uniqueKey?: string): Validator => (v,p) => {
  if (!Array.isArray(v) || v.length > 10000) fail(p);
  const seen = new Set<string>(); v.forEach((entry,i) => { validate(entry, `${p}[${i}]`); if (uniqueKey !== undefined) { const key = canonicalJson(uniqueKey ? (entry as Record<string, unknown>)[uniqueKey] : entry); if (seen.has(key)) fail(p); seen.add(key); } });
};
const object = (fields: Record<string, Validator>): Validator => (v,p) => {
  if (v === null || typeof v !== 'object' || Array.isArray(v) || Object.keys(v).length !== Object.keys(fields).length) fail(p);
  for (const [key,validator] of Object.entries(fields)) { if (!Object.hasOwn(v,key)) fail(`${p}.${key}`); validator((v as Record<string, unknown>)[key],`${p}.${key}`); }
};
const record = (validate: Validator): Validator => (v,p) => { if (v === null || typeof v !== 'object' || Array.isArray(v)) fail(p); for (const [key, entry] of Object.entries(v)) { text(key,p); validate(entry,`${p}.${key}`); } };
const uniqueStrings = array(text,'');
const provenanceValidator = object({ repositoryId:id, repository:repo, baseSha:sha, workflowBlobSha:sha, workflowPath:path, workflowHash:digest, jobId:text, stepIndex:integer, lockfileHash:digest, sourceTreeDigest:digest, verificationProfileHash:digest, toolSourceSha:sha, bundleDigest:digest });
const operationValidator = object({ type:literal('enable-pnpm-cache'), jobId:text, stepIndex:integer });
const profileValidator = object({ schemaVersion:literal(1), commands:array(array(text)), testReportPath:path, coverageReportPath:path, nodeVersion:semver, pnpmVersion:semver, timeoutSeconds:id, sourcePaths:array(path,'') });
const coverageValidator = object({ path, statements:integer, coveredStatements:integer, branches:integer, coveredBranches:integer, functions:integer, coveredFunctions:integer, lines:integer, coveredLines:integer });
const qualityValidator = object({ commandDigest:digest, tests:array(object({ id:text, outcome:literal('passed','failed','skipped') }),'id'), coverage:array(coverageValidator,'path') });
const baselineValidator = object({ runId:id, attempt:id, jobId:id, headSha:sha, conclusion:literal('success'), startedAt:timestamp, completedAt:timestamp, elapsedMs:number, installStepNumber:id, installElapsedMs:number, runnerLabels:uniqueStrings, runnerImage:nullable(text), requiredChecks:uniqueStrings });
const sampleValidator = object({ role:literal('base','candidate'), runId:id, attempt:id, jobId:id, headSha:sha, startedAt:timestamp, completedAt:timestamp, elapsedMs:number, roundedMinutes:integer, queueMs:number, endToEndMs:number, conclusion:literal('success','failure','cancelled','skipped'), runnerOs:text, runnerArchitecture:text, runnerImage:text, nodeVersion:text, pnpmVersion:text, workflowContractDigest:digest, sourceTreeDigest:digest, lockfileHash:digest, requiredChecks:array(object({ name:text, conclusion:text }),'name'), cacheObservation:literal('cold','hit','miss','not-applicable','unknown'), quality:qualityValidator });
const candidate = { candidateSha:sha, patchHash:digest };
const validators: Record<ArtifactKind, Validator> = {
  input: object({ schemaVersion:literal(1), kind:literal('input'), provenance:provenanceValidator, status:literal('collected','no-change','unsupported'), baselines:array(baselineValidator), structuralFacts:record((v,p) => { if (v !== null && typeof v !== 'boolean' && typeof v !== 'string' && typeof v !== 'number') fail(p); if (typeof v === 'number') number(v,p); if (typeof v === 'string') text(v,p); }), evidence:record(text), operations:array(operationValidator), requiredChecks:uniqueStrings }),
  diagnosis: object({ schemaVersion:literal(1), kind:literal('diagnosis'), provenance:provenanceValidator, status:literal('proposal','abstain'), reason:text, uncertainty:text, evidenceIds:uniqueStrings, operation:nullable(operationValidator), promptVersion:text, schemaVersionId:text, inferenceReceiptDigest:digest }),
  inference: object({ schemaVersion:literal(1), kind:literal('inference'), provenance:provenanceValidator, requestedModel:text, returnedModel:nullable(text), endpointHost:text, completionId:nullable(text), requestHash:digest, responseHash:nullable(digest), startedAt:timestamp, completedAt:timestamp, latencyMs:number, finishReason:nullable(text), usage:nullable(object({ promptTokens:integer, completionTokens:integer, totalTokens:integer })), quoteIdentity:nullable(text), costStatus:literal('known','unavailable','unknown'), cost:nullable(object({ amount:number, currency:text })), status:literal('completed','not-run','failed','outcome-unknown') }),
  proposal: object({ schemaVersion:literal(1), kind:literal('proposal'), provenance:provenanceValidator, ...candidate, candidateSha:nullable(sha), candidateWorkflowHash:digest, status:literal('proposed','no-change','rejected'), operation:operationValidator, beforeStructuralDigest:digest, afterStructuralDigest:digest, permittedDiff:object({ cache:literal('pnpm'), cacheDependencyPath:literal('pnpm-lock.yaml') }), preconditions:uniqueStrings, verificationProfile:profileValidator, diagnosisDigest:digest }),
  sandbox: object({ schemaVersion:literal(1), kind:literal('sandbox'), provenance:provenanceValidator, ...candidate, proposalDigest:digest, status:literal('sandbox-verified','failed','outcome-unknown'), image:object({ uuid:text, digest, recipeHash:digest, manifestHash:digest }), operations:array(object({ id:text, status:literal('PENDING','ASSIGNED','EXECUTING','SUCCESS','FAILED','CANCELLED'), role:literal('base','candidate'), exitCode:nullable(integer), signal:nullable(text), timedOut:bool, truncated:bool }),'id'), networkEnabled:literal(false), baseQuality:nullable(qualityValidator), candidateQuality:nullable(qualityValidator), startedAt:timestamp, completedAt:nullable(timestamp), elapsedMs:nullable(number), usage:nullable(object({ value:number, unit:text, currency:nullable(text) })), truncated:bool, cleanupState:literal('disposable-confirmed','pending','unknown'), retainedImage:literal(true) }),
  measurement: object({ schemaVersion:literal(1), kind:literal('measurement'), provenance:provenanceValidator, ...candidate, proposalDigest:digest, sandboxDigest:digest, cohortDigest:digest, status:literal('measured-improvement','no-improvement','rejected'), samples:array(sampleValidator), baselineMinutes:integer, candidateMinutes:integer, baselineMedianMs:number, candidateMedianMs:number, maximumQueueMs:number, maximumEndToEndMs:number, limits:uniqueStrings, claimLevel:literal('sample-execution-only','none'), githubListSavingUsd:number }),
  report: object({ schemaVersion:literal(1), kind:literal('report'), provenance:provenanceValidator, ...candidate, proposalDigest:digest, sandboxDigest:digest, measurementDigest:digest, status:literal('ready-to-publish','no-improvement','rejected'), markdown:text, markdownHash:digest, marker:text, baseRef:text, headRef:text }),
  publication: object({ schemaVersion:literal(1), kind:literal('publication'), provenance:provenanceValidator, ...candidate, reportHash:digest, authorizationDigest:digest, repository:repo, baseRef:text, headRef:text, baseSha:sha, headSha:sha, marker:text, status:literal('published','outcome-unknown','rejected'), number:nullable(id), url:nullable(text) }),
};
export function decodeProvenance(value: unknown): Provenance { canonicalJson(value); provenanceValidator(value,'provenance'); return value as Provenance; }
export function decodeVerificationProfile(value: unknown): VerificationProfile { canonicalJson(value); profileValidator(value,'profile'); const profile = value as VerificationProfile; if (!profile.commands.length || profile.commands.some(command => !command.length) || profile.timeoutSeconds > 600) fail('profile.commands/timeout'); return profile; }
export function decodeQualityEvidence(value: unknown): QualityEvidence { canonicalJson(value); qualityValidator(value,'quality'); const quality = value as QualityEvidence; for (const coverage of quality.coverage) for (const counter of ['Statements','Branches','Functions','Lines'] as const) { const denominator = counter.toLowerCase() as 'statements'|'branches'|'functions'|'lines'; if (coverage[`covered${counter}`] > coverage[denominator]) fail(`quality.coverage.${counter}`); } return quality; }
export function decodeArtifact<K extends ArtifactKind>(kind: K, value: unknown): ArtifactMap[K] {
  canonicalJson(value); validators[kind](value,kind); const artifact = value as ArtifactMap[K];
  if ('operation' in artifact && artifact.operation !== null && (artifact.operation.jobId !== artifact.provenance.jobId || artifact.operation.stepIndex !== artifact.provenance.stepIndex)) fail(`${kind}.operation.target`);
  if (artifact.kind === 'diagnosis' && ((artifact.status === 'proposal') !== (artifact.operation !== null) || (artifact.status === 'proposal' && !artifact.evidenceIds.length))) fail('diagnosis.operation/status');
  if (artifact.kind === 'inference' && artifact.usage !== null && artifact.usage.totalTokens !== artifact.usage.promptTokens + artifact.usage.completionTokens) fail('inference.usage.totalTokens');
  if (artifact.kind === 'inference' && (artifact.costStatus === 'known') !== (artifact.cost !== null)) fail('inference.costStatus');
  if (artifact.kind === 'proposal') decodeVerificationProfile(artifact.verificationProfile);
  if (artifact.kind === 'sandbox') { if (artifact.baseQuality) decodeQualityEvidence(artifact.baseQuality); if (artifact.candidateQuality) decodeQualityEvidence(artifact.candidateQuality); if (artifact.status === 'sandbox-verified' && (!artifact.baseQuality || !artifact.candidateQuality || artifact.truncated || artifact.cleanupState !== 'disposable-confirmed' || artifact.operations.length !== 2 || artifact.operations.some(op => op.status !== 'SUCCESS' || op.exitCode !== 0 || op.signal || op.timedOut || op.truncated))) fail('sandbox.verified'); }
  if (artifact.kind === 'measurement') artifact.samples.forEach(sample => decodeQualityEvidence(sample.quality));
  if (artifact.kind === 'publication' && artifact.status === 'published' && (!artifact.number || artifact.url !== `https://github.com/${artifact.repository}/pull/${artifact.number}`)) fail('publication.readback');
  if (artifact.kind === 'input') {
    if (artifact.operations.some(operation=>operation.jobId!==artifact.provenance.jobId||operation.stepIndex!==artifact.provenance.stepIndex)) fail('input.operation.target');
    if (artifact.status==='collected' && (!artifact.baselines.length || !artifact.requiredChecks.length || !Object.keys(artifact.evidence).length || artifact.operations.length!==1 || artifact.baselines.some(baseline=>!baseline.requiredChecks.length||baseline.requiredChecks.some(check=>!artifact.requiredChecks.includes(check))))) fail('input.collected.prerequisites');
    const attempts=new Set<string>();
    for (const baseline of artifact.baselines) { validateTiming(baseline.startedAt,baseline.completedAt,baseline.elapsedMs); if (baseline.headSha!==artifact.provenance.baseSha || baseline.installElapsedMs>baseline.elapsedMs) fail('input.baseline.identity'); const key=`${baseline.runId}:${baseline.attempt}:${baseline.jobId}`; if (attempts.has(key)) fail('input.baseline.duplicate'); attempts.add(key); }
  }
  if (artifact.kind === 'inference') {
    validateTiming(artifact.startedAt,artifact.completedAt,artifact.latencyMs);
    if (artifact.status==='completed' && (!artifact.requestedModel.startsWith('nvidia/') || artifact.returnedModel!==artifact.requestedModel || artifact.finishReason!=='stop' || !artifact.responseHash || !artifact.completionId || !['api.tokenfactory.nebius.com'].includes(artifact.endpointHost))) fail('inference.completed.identity');
  }
  if (artifact.kind === 'sandbox' && artifact.status==='sandbox-verified') {
    if (!artifact.completedAt || artifact.elapsedMs===null || artifact.operations.filter(op=>op.role==='base').length!==1 || artifact.operations.filter(op=>op.role==='candidate').length!==1 || !artifact.baseQuality?.tests.length || !artifact.candidateQuality?.tests.length || !artifact.baseQuality.coverage.length || !artifact.candidateQuality.coverage.length) fail('sandbox.verified.pair');
    validateTiming(artifact.startedAt,artifact.completedAt,artifact.elapsedMs);
  }
  if (artifact.kind === 'measurement') { const attempts=new Set<string>(); for (const sample of artifact.samples) { validateTiming(sample.startedAt,sample.completedAt,sample.elapsedMs); const key=`${sample.runId}:${sample.attempt}:${sample.jobId}`; if (attempts.has(key)) fail('measurement.duplicate'); attempts.add(key); } }
  if (artifact.kind === 'report' && sha256(artifact.markdown)!==artifact.markdownHash) fail('report.markdownHash');
  return artifact;
}
export function assertSameProvenance(left: Provenance, right: Provenance): void { if (canonicalJson(decodeProvenance(left)) !== canonicalJson(decodeProvenance(right))) throw new OptimizationInputError('Immutable provenance drift; recollect input'); }
export function validateDiagnosisEvidence(diagnosis: DiagnosisArtifact, input: InputArtifact): void { assertSameProvenance(diagnosis.provenance,input.provenance); if (diagnosis.evidenceIds.some(id => !Object.hasOwn(input.evidence,id))) fail('diagnosis.evidenceIds.unknown'); if (diagnosis.operation && !input.operations.some(operation => canonicalJson(operation) === canonicalJson(diagnosis.operation))) fail('diagnosis.operation.unsupported'); }

function validateTiming(startedAt:string,completedAt:string,elapsedMs:number):void { if (Date.parse(completedAt)-Date.parse(startedAt)!==elapsedMs) fail('timing.elapsedMs'); }
export function decodeActionReceipt(value:unknown):ActionReceipt {
  canonicalJson(value); object({repository:literal('actions/setup-node'),commitSha:sha,releaseTag:literal('v7.0.0'),releaseId:id,immutable:literal(true),actionHash:digest,inputs:uniqueStrings,outputs:uniqueStrings,retrievedAt:timestamp})(value,'actionReceipt');
  const receipt=value as ActionReceipt;
  if (receipt.commitSha!=='820762786026740c76f36085b0efc47a31fe5020' || receipt.releaseId!==353541365 || receipt.actionHash!=='5d765941ab5d8bef27f08e81b0b041cdb2df2050ea0261dc925d157a2bafbd2b' || !receipt.inputs.includes('cache') || !receipt.inputs.includes('cache-dependency-path') || !receipt.outputs.includes('cache-hit')) fail('actionReceipt.official-v7');
  return receipt;
}
export interface SourceManifest {schemaVersion:1;provenance:Provenance;profilePath:string;files:{path:string;mode:'100644'|'100755';hash:string;bytesBase64:string}[]}
export function decodeSourceManifest(value:unknown):SourceManifest {
  canonicalJson(value);object({schemaVersion:literal(1),provenance:provenanceValidator,profilePath:path,files:array(object({path,mode:literal('100644','100755'),hash:digest,bytesBase64:sourceBytes}),'path')})(value,'source');
  const manifest=value as SourceManifest;
  if(manifest.files.length>5000) fail('source.files.limit'); let totalBytes=0;
  for (const file of manifest.files) { const bytes=Buffer.from(file.bytesBase64,'base64'); totalBytes+=bytes.length; if (bytes.length>4*1024*1024 || totalBytes>16*1024*1024 || file.path.split('/').includes('.git') || /(?:^|\/)(?:\.env(?:\..*)?|\.npmrc|credentials(?:\..*)?|id_rsa|id_ed25519|[^/]*\.(?:pem|key))$/.test(file.path)) fail('source.file.sensitive-or-size'); if(bytes.toString('base64')!==file.bytesBase64 || sha256(bytes)!==file.hash) fail('source.file.hash'); }
  const workflow=manifest.files.find(file=>file.path===manifest.provenance.workflowPath),lockfile=manifest.files.find(file=>file.path==='pnpm-lock.yaml'),profile=manifest.files.find(file=>file.path===manifest.profilePath);
  if (!workflow || gitBlobSha(Buffer.from(workflow.bytesBase64,'base64'))!==manifest.provenance.workflowBlobSha || workflow.hash!==manifest.provenance.workflowHash || !lockfile || lockfile.hash!==manifest.provenance.lockfileHash || !profile || profile.hash!==manifest.provenance.verificationProfileHash) fail('source.provenance');
  const tree=manifest.files.filter(file=>file.path!==manifest.provenance.workflowPath).map(({path,mode,hash})=>({path,mode,hash})).sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0);
  if (sha256(canonicalJson(tree))!==manifest.provenance.sourceTreeDigest) fail('source.treeDigest');return manifest;
}
