import { describe, expect, it } from 'vitest';
import { jsonDigest } from './canonical.js';
import { assertMeasuredEvidence, compareMeasurement, decodeCohortManifest } from './measurement.js';
import { measurementFixture, setTiming } from './measurement.test-helper.js';
import type { ComparisonInputs } from './measurement.js';

describe('immutable measurement cohort', () => {
  it('accepts six predefined attempts, including a cohort recorded after reused runs', () => { const input = measurementFixture(); expect(decodeCohortManifest(input.cohort)).toEqual(input.cohort); });
  it.each(['extra', 'missing', 'order', 'duplicate', 'timestamp', 'candidate', 'runner'] as const)('rejects malformed %s', mutation => { const cohort = measurementFixture().cohort; const raw = cohort as unknown as Record<string, unknown>; if (mutation === 'extra') raw.extra = true; if (mutation === 'missing') delete raw.runner; if (mutation === 'order') cohort.entries[0]!.role = 'candidate'; if (mutation === 'duplicate') cohort.entries[1]!.runId = cohort.entries[0]!.runId; if (mutation === 'timestamp') cohort.recordedAt = '2026-02-30T00:00:00Z'; if (mutation === 'candidate') cohort.candidateSha = 'bad'; if (mutation === 'runner') (cohort.runner as unknown as Record<string, unknown>).other = true; expect(() => decodeCohortManifest(cohort)).toThrow(); });
});

describe('whole-job comparison', () => {
  it('measures only six matching samples, cold first, including queue and end-to-end disclosure', () => { const inputs = measurementFixture(); const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('measured-improvement'); expect(artifact.claimLevel).toBe('sample-execution-only'); expect(artifact.baselineMinutes).toBe(6); expect(artifact.candidateMinutes).toBe(3); expect(artifact.baselineMedianMs).toBe(120000); expect(artifact.candidateMedianMs).toBe(60000); expect(artifact.maximumQueueMs).toBe(5000); expect(artifact.maximumEndToEndMs).toBe(122000); expect(artifact.samples).toEqual(inputs.samples); expect(artifact.githubListSavingUsd).toBe(0); expect(artifact.cohortDigest).toBe(jsonDigest(inputs.cohort)); expect(artifact.limits).toContain('sample-execution-only'); expect(artifact.limits).toContain('cold-candidate-included'); expect(artifact.limits).toContain('provider-inference-costs-not-netted'); assertMeasuredEvidence(inputs, artifact); });
  it('resolves the immutable pre-commit proposal through verified Sandbox candidate evidence',()=>{const inputs=measurementFixture(),candidateSha=inputs.sandbox.candidateSha;inputs.proposal.candidateSha=null;inputs.sandbox.proposalDigest=jsonDigest(inputs.proposal);inputs.cohort.proposalDigest=jsonDigest(inputs.proposal);inputs.cohort.sandboxDigest=jsonDigest(inputs.sandbox);const artifact=compareMeasurement(inputs);expect(artifact.status).toBe('measured-improvement');expect(artifact.candidateSha).toBe(candidateSha);});
  it('rounds each complete job at exact minute boundaries', () => { const inputs = measurementFixture(); inputs.samples.slice(0, 3).forEach(sample => setTiming(sample, 60001)); inputs.samples.slice(3).forEach(sample => setTiming(sample, 54000)); const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('measured-improvement'); expect(artifact.baselineMinutes).toBe(6); expect(artifact.candidateMinutes).toBe(3); });
  it.each([60000, 59999])('retains no improvement when rounding does not save a minute at %i', baselineMs => { const inputs = measurementFixture(); inputs.samples.slice(0, 3).forEach(sample => setTiming(sample, baselineMs)); inputs.samples.slice(3).forEach(sample => setTiming(sample, 50000)); const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('no-improvement'); expect(artifact.claimLevel).toBe('none'); expect(artifact.githubListSavingUsd).toBe(0); });
  it('requires at least ten percent lower median even when rounded minutes fall', () => { const inputs = measurementFixture(); inputs.samples.slice(0, 3).forEach(sample => setTiming(sample, 60001)); inputs.samples.slice(3).forEach(sample => setTiming(sample, 59000)); expect(compareMeasurement(inputs).status).toBe('no-improvement'); });
  it('accepts exactly ten percent lower median', () => { const inputs = measurementFixture(); inputs.samples.slice(0, 3).forEach(sample => setTiming(sample, 100000)); inputs.samples.slice(3).forEach(sample => setTiming(sample, 90000)); setTiming(inputs.samples[3]!, 60000); expect(compareMeasurement(inputs).status).toBe('measured-improvement'); });
  it('does not claim a cold run was included when the observation is missing', () => { const inputs = measurementFixture(); inputs.samples[3]!.cacheObservation = 'unknown'; const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('rejected'); expect(artifact.limits).not.toContain('cold-candidate-included'); expect(artifact.limits).toContain('cold-candidate-required'); });
  it.each(['earlier', 'simultaneous'])('rejects a %s warm execution before the declared cold candidate', order => { const inputs = measurementFixture(); const warm = inputs.samples[4]!; warm.startedAt = new Date(Date.parse(inputs.samples[3]!.startedAt) - (order === 'earlier' ? 600000 : 0)).toISOString(); setTiming(warm, warm.elapsedMs); const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('rejected'); expect(artifact.limits).toContain('candidate-chronology-invalid'); });
  it('retains failed samples rather than selecting successful replacements', () => { const inputs = measurementFixture(); inputs.samples[4]!.conclusion = 'failure'; const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('rejected'); expect(artifact.samples).toHaveLength(6); expect(artifact.samples[4]!.conclusion).toBe('failure'); expect(artifact.limits).toContain('sample-failed'); });
  const mutants: [string, (inputs: ComparisonInputs) => void][] = [
    ['head SHA', i => { i.samples[4]!.headSha = 'f'.repeat(40); }], ['attempt', i => { i.samples[4]!.attempt = 2; }], ['run membership', i => { i.samples[4]!.runId = 70; }], ['sample order', i => { [i.samples[0], i.samples[1]] = [i.samples[1]!, i.samples[0]!]; }], ['missing sample', i => { i.samples.pop(); }], ['runtime', i => { i.samples[4]!.nodeVersion = '22.19.0'; }], ['pnpm', i => { i.samples[4]!.pnpmVersion = '10.17.0'; }], ['runner image', i => { i.samples[4]!.runnerImage = 'other'; }], ['runner architecture', i => { i.samples[4]!.runnerArchitecture = 'ARM64'; }], ['source', i => { i.samples[4]!.sourceTreeDigest = 'e'.repeat(64); }], ['lockfile', i => { i.samples[4]!.lockfileHash = 'e'.repeat(64); }], ['workflow contract', i => { i.samples[4]!.workflowContractDigest = 'e'.repeat(64); }], ['structural drift', i => { i.proposal.afterStructuralDigest = 'e'.repeat(64); }], ['rounding', i => { i.samples[4]!.roundedMinutes = 0; }], ['required check failure', i => { i.samples[4]!.requiredChecks[0]!.conclusion = 'failure'; }], ['missing check', i => { i.samples[4]!.requiredChecks = []; }], ['extra check', i => { i.samples[4]!.requiredChecks.push({ name: 'uncollected', conclusion: 'success' }); }], ['cold omission', i => { i.samples[3]!.cacheObservation = 'hit'; }], ['unknown cache', i => { i.samples[4]!.cacheObservation = 'unknown'; }], ['candidate not applicable cache', i => { i.samples[4]!.cacheObservation = 'not-applicable'; }], ['test loss', i => { i.samples[4]!.quality.tests.pop(); }], ['skipped test changed', i => { i.samples[4]!.quality.tests[1]!.outcome = 'passed'; }], ['test failure', i => { i.samples[4]!.quality.tests[0]!.outcome = 'failed'; }], ['coverage denominator', i => { i.samples[4]!.quality.coverage[0]!.statements++; }], ['coverage count', i => { i.samples[4]!.quality.coverage[0]!.coveredStatements--; }], ['command change', i => { i.samples[4]!.quality.commandDigest = 'e'.repeat(64); }], ['sandbox quality', i => { i.sandbox.candidateQuality!.coverage[0]!.lines++; }], ['profile path inventory', i => { i.proposal.verificationProfile.sourcePaths.push('src/uncovered.ts'); }], ['empty tests', i => { i.samples[4]!.quality.tests = []; }], ['empty coverage', i => { i.samples[4]!.quality.coverage = []; }], ['end to end incomplete', i => { i.samples[4]!.endToEndMs = 0; }], ['input unsupported', i => { i.input.status = 'unsupported'; }], ['proposal rejected', i => { i.proposal.status = 'rejected'; }], ['sandbox failed', i => { i.sandbox.status = 'failed'; }], ['cohort binding', i => { i.cohort.proposalDigest = 'e'.repeat(64); }], ['sandbox binding', i => { i.sandbox.proposalDigest = 'e'.repeat(64); }], ['provenance', i => { i.samples[4]!.lockfileHash = 'e'.repeat(64); }],
  ];
  it.each(mutants)('rejects %s drift and preserves provided evidence', (_, mutate) => { const inputs = measurementFixture(); mutate(inputs); const artifact = compareMeasurement(inputs); expect(artifact.status).toBe('rejected'); expect(artifact.claimLevel).toBe('none'); expect(artifact.samples).toEqual(inputs.samples); expect(artifact.githubListSavingUsd).toBe(0); });
  it('normalizes order of quality IDs and counters without weakening identity', () => { const inputs = measurementFixture(); inputs.samples[4]!.quality.tests.reverse(); expect(compareMeasurement(inputs).status).toBe('measured-improvement'); });
  it('throws for malformed timing or sample schema instead of laundering it', () => { const inputs = measurementFixture(); inputs.samples[4]!.completedAt = '2026-09-29T10:02:00Z'; expect(() => compareMeasurement(inputs)).toThrow(); setTiming(inputs.samples[4]!, 60000); (inputs.samples[4] as unknown as Record<string, unknown>).extra = true; expect(() => compareMeasurement(inputs)).toThrow(); });
  it('does not mutate caller artifacts and rows', () => { const inputs = measurementFixture(); const before = jsonDigest(inputs); compareMeasurement(inputs); expect(jsonDigest(inputs)).toBe(before); });
});

describe('bounded financial claims and evidence revalidation', () => {
  it('public repository list saving remains zero with a supplied price', () => { const inputs = measurementFixture(); inputs.pricing = { usdPerMinute: 0.006, priceBasis: 'owner approved standard Linux quote 2026-09-29', allowanceKnown: true }; expect(compareMeasurement(inputs).githubListSavingUsd).toBe(0); });
  it('private explicit known pricing yields a list estimate, never invoice or net savings', () => { const inputs = measurementFixture(); inputs.visibility = 'private'; inputs.pricing = { usdPerMinute: 0.006, priceBasis: 'owner approved standard Linux quote 2026-09-29', allowanceKnown: true }; const artifact = compareMeasurement(inputs); expect(artifact.githubListSavingUsd).toBeCloseTo(0.018, 10); expect(artifact.limits).toContain('list-price-estimate-not-invoice'); expect(artifact.limits).toContain('provider-inference-costs-not-netted'); });
  it.each(['missing', 'allowance'] as const)('does not invent private savings with %s pricing context', kind => { const inputs = measurementFixture(); inputs.visibility = 'private'; if (kind === 'allowance') inputs.pricing = { usdPerMinute: 0.006, priceBasis: 'explicit quote', allowanceKnown: false }; const artifact = compareMeasurement(inputs); expect(artifact.githubListSavingUsd).toBe(0); expect(artifact.limits).toContain(kind === 'missing' ? 'github-pricing-unavailable' : 'github-allowance-unknown'); });
  it.each(['price', 'basis', 'keys', 'visibility'] as const)('rejects malformed %s', kind => { const inputs = measurementFixture(); inputs.pricing = { usdPerMinute: 0.006, priceBasis: 'explicit quote', allowanceKnown: true }; if (kind === 'price') inputs.pricing.usdPerMinute = -1; if (kind === 'basis') inputs.pricing.priceBasis = ''; if (kind === 'keys') (inputs.pricing as unknown as Record<string, unknown>).extra = 1; if (kind === 'visibility') (inputs as unknown as Record<string, unknown>).visibility = 'internal'; expect(() => compareMeasurement(inputs)).toThrow(); });
  it.each(['status', 'amount', 'sample', 'limits', 'digest'] as const)('recomputes complete evidence and rejects forged %s', kind => { const inputs = measurementFixture(); const artifact = compareMeasurement(inputs); if (kind === 'status') artifact.status = 'no-improvement'; if (kind === 'amount') artifact.githubListSavingUsd = 42; if (kind === 'sample') artifact.samples[4]!.quality.tests.pop(); if (kind === 'limits') artifact.limits = []; if (kind === 'digest') artifact.cohortDigest = 'e'.repeat(64); expect(() => assertMeasuredEvidence(inputs, artifact)).toThrow(); });
});
