import { jsonDigest } from './canonical.js';
import type { ComparisonInputs } from './measurement.js';
import type { MeasurementSample, QualityEvidence, VerificationProfile } from './contracts.js';

export function measurementFixture(): ComparisonInputs {
  const profile: VerificationProfile = { schemaVersion: 1, commands: [['pnpm', 'test']], testReportPath: 'quality.json', coverageReportPath: 'coverage/coverage-final.json', nodeVersion: '22.20.0', pnpmVersion: '10.17.1', timeoutSeconds: 600, sourcePaths: ['src/a.ts'] };
  const provenance = { repositoryId: 1, repository: 'owner/project', baseSha: 'a'.repeat(40), workflowBlobSha: 'b'.repeat(40), workflowPath: '.github/workflows/ci.yml', workflowHash: 'a'.repeat(64), jobId: 'test', stepIndex: 2, lockfileHash: 'b'.repeat(64), sourceTreeDigest: 'c'.repeat(64), verificationProfileHash: jsonDigest(profile), toolSourceSha: 'c'.repeat(40), bundleDigest: 'd'.repeat(64) };
  const quality: QualityEvidence = { commandDigest: jsonDigest([['pnpm', 'install', '--frozen-lockfile'], ...profile.commands]), tests: [{ id: 'src/a.test.ts:passes', outcome: 'passed' }, { id: 'src/a.test.ts:skips', outcome: 'skipped' }], coverage: [{ path: 'src/a.ts', statements: 3, coveredStatements: 2, branches: 2, coveredBranches: 1, functions: 1, coveredFunctions: 1, lines: 3, coveredLines: 2 }] };
  const operation = { type: 'enable-pnpm-cache' as const, jobId: 'test', stepIndex: 2 };
  const input: ComparisonInputs['input'] = { schemaVersion: 1, kind: 'input', provenance, status: 'collected', baselines: [{ runId: 1, attempt: 1, jobId: 101, headSha: provenance.baseSha, conclusion: 'success', startedAt: '2026-09-29T10:00:00Z', completedAt: '2026-09-29T10:02:00Z', elapsedMs: 120000, installStepNumber: 4, installElapsedMs: 50000, runnerLabels: ['ubuntu-latest'], runnerImage: 'ubuntu24-20260920', requiredChecks: ['test'] }], structuralFacts: { eligible: true }, evidence: { install: 'install duration' }, operations: [operation], requiredChecks: ['test'] };
  const proposal: ComparisonInputs['proposal'] = { schemaVersion: 1, kind: 'proposal', provenance, status: 'proposed', operation, candidateSha: 'd'.repeat(40), candidateWorkflowHash: 'e'.repeat(64), patchHash: 'f'.repeat(64), beforeStructuralDigest: '1'.repeat(64), afterStructuralDigest: '1'.repeat(64), permittedDiff: { cache: 'pnpm', cacheDependencyPath: 'pnpm-lock.yaml' }, preconditions: ['verified'], verificationProfile: profile, diagnosisDigest: '2'.repeat(64) };
  const sandbox: ComparisonInputs['sandbox'] = { schemaVersion: 1, kind: 'sandbox', provenance, candidateSha: proposal.candidateSha!, patchHash: proposal.patchHash, proposalDigest: jsonDigest(proposal), status: 'sandbox-verified', image: { uuid: 'approved-image', digest: '3'.repeat(64), recipeHash: '4'.repeat(64), manifestHash: '5'.repeat(64) }, operations: ['base', 'candidate'].map(role => ({ id: `operation-${role}`, status: 'SUCCESS' as const, role: role as 'base' | 'candidate', exitCode: 0, signal: null, timedOut: false, truncated: false })), networkEnabled: false, baseQuality: structuredClone(quality), candidateQuality: structuredClone(quality), startedAt: '2026-09-29T10:00:00Z', completedAt: '2026-09-29T10:00:10Z', elapsedMs: 10000, usage: { value: 0.01, unit: 'undocumented-provider-unit', currency: null }, truncated: false, cleanupState: 'disposable-confirmed', retainedImage: true };
  const samples: MeasurementSample[] = Array.from({ length: 6 }, (_, index) => { const candidate = index >= 3; const elapsedMs = candidate ? 60000 : 120000; return { role: candidate ? 'candidate' : 'base', runId: index + 1, attempt: 1, jobId: 101 + index, headSha: candidate ? proposal.candidateSha! : provenance.baseSha, startedAt: new Date(Date.parse('2026-09-29T10:00:00Z') + index * 600000).toISOString(), completedAt: new Date(Date.parse('2026-09-29T10:00:00Z') + index * 600000 + elapsedMs).toISOString(), elapsedMs, roundedMinutes: candidate ? 1 : 2, queueMs: index * 1000, endToEndMs: elapsedMs + index * 1000, conclusion: 'success', runnerOs: 'Linux', runnerArchitecture: 'X64', runnerImage: 'ubuntu24-20260920', nodeVersion: profile.nodeVersion, pnpmVersion: profile.pnpmVersion, workflowContractDigest: proposal.beforeStructuralDigest, sourceTreeDigest: provenance.sourceTreeDigest, lockfileHash: provenance.lockfileHash, requiredChecks: [{ name: 'test', conclusion: 'success' }], cacheObservation: candidate ? index === 3 ? 'cold' : 'hit' : 'not-applicable', quality: structuredClone(quality) }; });
  return { input, proposal, sandbox, samples, visibility: 'public', pricing: null, cohort: { schemaVersion: 1, kind: 'measurement-cohort', provenance, proposalDigest: jsonDigest(proposal), sandboxDigest: jsonDigest(sandbox), candidateSha: proposal.candidateSha!, recordedAt: '2026-09-29T11:00:00Z', entries: samples.map(({ role, runId, attempt }) => ({ role, runId, attempt })), runner: { os: 'Linux', architecture: 'X64', image: 'ubuntu24-20260920' } } };
}

export function setTiming(sample: MeasurementSample, elapsedMs: number): void { sample.elapsedMs = elapsedMs; sample.completedAt = new Date(Date.parse(sample.startedAt) + elapsedMs).toISOString(); sample.roundedMinutes = Math.ceil(elapsedMs / 60000); sample.endToEndMs = sample.queueMs + elapsedMs; }
